### ISSUE TITLE
Tracker for Numba usability improvements.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2888]
Following on from: https://github.com/numba/numba/issues/2788

New user facing documentation/web pages, to include:
- [x]  ~~A one page guide to Numba.~~ Done in https://github.com/numba/numba/pull/3132
- [ ]  Numba decorators+flags explained.
- [x]  "Cool stuff"/new features page (EDIT: each release gets a demo notebook!)
- [ ]  Explain our DSO infrastructure especially with respect to LLVM (there are a lot of questions about this).
- [ ]  "how @jit works" page, high level with pictures etc
- [x]  ~~How to make Numba perform well and a quick guide to achieving good performance.~~ Done in https://github.com/numba/numba/pull/2877

An exceptions catch-all and backtrace hiding/rewriting facility to make exceptions more user friendly (and enabled by default, devs will want to turn this off!). The rewrite facility to include:
  - [x] ~~Provision of better and more user friendly error messages.~~ Done in https://github.com/numba/numba/pull/2859
  - [x] ~~More effort to find the offending line number(s).~~ Done in https://github.com/numba/numba/pull/2859
  - [x] ~~Printing the offending line (helps in Jupyter/ipython).~~ Done in https://github.com/numba/numba/pull/2859
  - [ ] Possibly raising exception classes that are user orientated and are not named after language from compiler design.
  - [x] ~~New documentation pages with explanations and examples of common problems that can be inserted into Exception messages as links.~~ Done in https://github.com/numba/numba/pull/2859
  - [ ] Debug hints if applicable (common issues, like use of unsupported types, non-homogeneous lists etc).
  - [x] An Exception class for when there is likely a problem with Numba internals with instructions for users on how to report it.

Additional features:
- [x] ~~Bug report template~~ Done in https://github.com/numba/numba/pull/2880
- [x] ~~Updates to the Numba annotation tool.~~ Done in https://github.com/numba/numba/pull/2793
- [ ] Ensure that the feature support documentation is accurate.

Then from a developer side we are aware that we need to:

- [ ] Write documentation on how to extend Numba and integrate it with existing code bases.
- [x] Write documentation on how to write new features in Numba without essentially having to build up LLVM IR using llvmlite builder classes (Using `@overload` and `@intrinsic`).
- [ ] Go through the existing documentation and ensure that the user documentation is accurate and that anything that is a Numba implementation/technical detail goes into the developer side documentation.

**Comment by jni** [comment]
Hi everyone! As prompted by @stuartarchibald in https://github.com/scisprints/2018_05_sklearn_skimage_dask/issues/9, I'll use this issue to report my wishlist/experiences with Numba performance/debugging and how they could be better. Some may be already solved without my knowledge.

- [ ] Add debugging tips documentation. I tend to run my tests both with JIT and with NUMBA_DISABLE_JIT=1. This is helpful to make sure that any failures are not due to the JIT doing something different from Python (for example, no modifying of globals in JIT), to drop into pdb when things go wrong, and to measure test coverage.
- [ ] #2793 is probably the biggest item on my wishlist. The Cython HTML output is its killer app, especially when starting to learn Cython, but even as an advanced user I use it all the time. This would probably really help with various issues on the mailing list, such as [this one](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/numba-users/I1b8onUVBuM/0Km3UPSEBQAJ) or [this one](https://groups.google.com/a/continuum.io/forum/#!msg/numba-users/pAEPXJVb_CM/_qhsO8jVAQAJ), where I was told that the best way to optimize Numba performance was to ask on the mailing list. This was admittedly almost two years ago, but at the same time, the new [performance tips](http://numba.pydata.org/numba-doc/0.38.0/user/performance-tips.html) don't address either of these issues.
- [ ] Cython allows the use of a profiler, and provides an [extensive guide](http://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html) for how to do so. This was recently invaluable to [track down](https://github.com/scikit-image/scikit-image/issues/2636#issuecomment-332731333) a performance regression in scikit-image. It is hard to see how I would have achieved the same thing with a Numba-based problem.

Hope this helps, and thank you!

**Comment by seibert** [comment]
Great, these are all good suggestions!

**Comment by stuartarchibald** [comment]
Closing, there's a summary of the improvements along with additional new features/new tickets here: https://github.com/numba/numba/issues/2788

**Comment by stuartarchibald** [comment]
> Hi everyone! As prompted by @stuartarchibald in [scisprints/2018_05_sklearn_skimage_dask#9](https://github.com/scisprints/2018_05_sklearn_skimage_dask/issues/9), I'll use this issue to report my wishlist/experiences with Numba performance/debugging and how they could be better. Some may be already solved without my knowledge.
> 
>     * [ ]  Add debugging tips documentation. I tend to run my tests both with JIT and with NUMBA_DISABLE_JIT=1. This is helpful to make sure that any failures are not due to the JIT doing something different from Python (for example, no modifying of globals in JIT), to drop into pdb when things go wrong, and to measure test coverage.

Added [here](https://numba.readthedocs.io/en/stable/user/faq.html#can-i-debug-a-jitted-function)

>     * [ ]  #2793 is probably the biggest item on my wishlist. The Cython HTML output is its killer app, especially when starting to learn Cython, but even as an advanced user I use it all the time. This would probably really help with various issues on the mailing list, such as [this one](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/numba-users/I1b8onUVBuM/0Km3UPSEBQAJ) or [this one](https://groups.google.com/a/continuum.io/forum/#!msg/numba-users/pAEPXJVb_CM/_qhsO8jVAQAJ), where I was told that the best way to optimize Numba performance was to ask on the mailing list. This was admittedly almost two years ago, but at the same time, the new [performance tips](http://numba.pydata.org/numba-doc/0.38.0/user/performance-tips.html) don't address either of these issues.

Numba has in general moved away from the notion of a "mixed" compilation mode. `nopython` mode is recommended and, assuming Numba can compile the code, there's no CPython API level calls present.

>     * [ ]  Cython allows the use of a profiler, and provides an [extensive guide](http://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html) for how to do so. This was recently invaluable to [track down](https://github.com/scikit-image/scikit-image/issues/2636#issuecomment-332731333) a performance regression in scikit-image. It is hard to see how I would have achieved the same thing with a Numba-based problem.

Profiler development is tracked in https://github.com/numba/numba/issues/5028.
