### ISSUE TITLE
Numba 0.38 RC checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#2892]
- [x] Check on random permutation test fail in buildbot
- [x] Rebuild icc_rt packages in Numba channel after #2881 is merged
- [x] Verify SVML still working with icc_rt packages (win/mac/linux 64-bit)
- [x] Verify Twine patch is present in latest llvmdev builds
- [x] Unskip viewcfg tests in Numba (originally triggered the Twine bug)
- [x] llvmlite changelog
- [x] llvmlite RC tag and build conda packages
- [x] Merge remaining 0.38 milestone PRs
- [x] Verify build is stable on buildbot
- [x] Write Numba changelog PR
- [x] Tag and build RC
- [x] Verify dev docs up to date
- [x] Verify RC conda packages in numba channel
- [x] Announce on email list and Twitter

**Comment by seibert** [comment]
Boom! Done.
