### ISSUE TITLE
Numba 0.40.0 RC Checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#3299]
## llvmlite

* [ ] Any pending PRs ready to merge?
* [ ] update changelog
* [ ] tag 0.25.0
* [ ] verify packages uploaded to Anaconda Cloud

## numba

* [ ] Merge #3186 once win64 CUDA CI success confirmed
* [ ] Merge #3259 once CUDA CI success confirmed on Linux
* [ ] Hide ARMv7 instructions, update text and merge #3274
* [ ] Review and merge #3202 
* [ ] Review and merge #3166 
* [ ] Finish and merge changelog #3296
* [ ] Update conda build recipes to pin to new llvmlite and run_constraints to pick latest TBB.
* [ ] Create 0.40 branch
* [ ] Tag empty commit for 0.40.0rc1 on branch
* [ ] Build conda packages on build farm
* [ ] Verify packages uploaded to Anaconda Cloud
* [ ] Send RC announcement email
* [ ] Post link to twitter
