### ISSUE TITLE
0.40.0 Final Release Checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#3317]
## llvmlite

* [x] Tag 0.25.0
* [x] Build conda packages on build farm (tag will not automatically trigger new build)
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels
   - Python [2.7, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI

## numba
* [x] Merge #3316 to master
* [x] Merge #3318 to master
* [x] Cherry pick #3310 to `release0.40` branch
* [x] Cherry pick #3316 to `release0.40` branch
* [x] Cherry pick #3318 to `release0.40` branch
* [x] Tag `0.40.0` on branch
* [x] Build conda packages on build farm [in progress]
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels
   - Python [2.7, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI
* [x] Upload 0.40.0 Numba docs, update `latest` link
* [x] Fix references to `dev` docs on Numba page to point to `latest`
* [x] Send announcement email
* [x] Post link to twitter

## On completion
* [x] Contact distribution team to start build out for main channels (in queue after next Anaconda release)

**Comment by seibert** [comment]
Done!  Let's do this again in 2 months.  :)
