### ISSUE TITLE
[Discussion][Umbrella] Parallel backend tasks

### ISSUE THREAD

**Issue by anton-malakhov** [numba/numba#3421]
Here are potential tasks concerning parallel backends, please add more as you find new ideas or issues

## Vectorization and parallelism
- [ ] Make @guvectorize and @vectorize being able to parallelize and SIMD-vectorize on the same 1D arguments
- [ ] Move partitioning logic from PA to the threading layers. 
- [ ] Move reduction logic to threading layers if seen beneficial

## OpenMP layer
- [ ] separate C extension names of  omppool compiled with for specific OpenMP vendors
- [ ] test loading of omppool in a forked process in order to detect if it causes any issues and whether it can be enabled
- [ ] detect conflicting openmp runtimes being loaded in the same process
- [ ] Reenable OpenMP threading backend in wheel builds #3400

## TBB layer
- [ ] Reduce gap in performance with OpenMP using affinity in collaboration with global settings functionality provided by tbb4py [future extension] or when requested through env vars or `numba` entry point
- [ ] Use TBB's [blocked_rangeNd](https://www.threadingbuildingblocks.org/docs/help/reference/appendices/preview_features/blocked_rangeNd_cls.html) or implement alternative aligned_rangeNd as run-time 

@stuartarchibald

**Comment by stuartarchibald** [comment]
Thanks for recording this @anton-malakhov. We've discussed most of this over a variety of channels so it's great to have it all in one place!
