### ISSUE TITLE
Numba 0.41 RC checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#3507]
## llvmlite

* [x] Any pending PRs ready to merge? (~~numba/llvmlite#389~~(unstable), numba/llvmlite#398, numba/llvmlite#399)
    * [x] merge numba/llvmlite#398, numba/llvmlite#399 
* [x] update changelog (numba/llvmlite#421)
* [x] tag 0.26.0rc1
* [x] verify conda packages uploaded to Anaconda Cloud
* [x] move packages from dev to main label

## numba

* [x] ~~Update install docs to describe ARMv7 install?~~ (holding until 0.42)
* [x] Merge #3511 (fix make_function literals, pending approval)
* [x] Merge #3449 (matching non-array objects in find_callname(), pending fix)
* [x] Merge #3506 (string docs, pending approval)
* [x] Merge #3513 (parallel diagnostics docs, ready to merge)
* [x] Merge changelog (#3512)
* [x] ~~Update conda build recipes to pin to new llvmlite~~ (already done a while ago)
* [x] switch build farm into release mode
* [x] Create 0.41 branch
* [x] Tag empty commit for 0.41.0rc1 on branch
* [x] Build conda packages on build farm
* [x] Verify conda packages uploaded to Anaconda Cloud
* [x] switch build farm into dev mode
* [x] Send RC announcement email
* [ ] Post link to twitter
