### ISSUE TITLE
Numba 0.41.0 final release checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#3537]
## llvmlite

* [x] Tag 0.26.0
* [x] Build conda packages on build farm (tag will not automatically trigger new build)
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels
   - Python [2.7, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI

## numba
* [x] ~Review and~ merge #3536 to master
* [x] ~Review and~ merge #3530 to master
* [x] ~Review and~ merge #3527 to master
* [x] Merge #3526 to master
* [x] Merge #3514 to master
* [x] Merge PR #3539 (Changelog update)
* [x] Cherry pick #3514 to `release0.41` branch
* [x] Cherry pick #3526 to `release0.41` branch
* [x] Cherry pick #3527 to `release0.41` branch
* [x] Cherry pick #3530 to `release0.41` branch
* [x] Cherry pick #3536 to `release0.41` branch
* [x] Cherry pick #3539 to `release0.41` branch
* [x] Tag `0.41.0` on branch
* [x] Switch build farm to shipping mode
* [x] Build conda packages on build farm
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Switch build farm to development mode
* [x] Build wheels
   - Python [2.7, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI
* [x] Upload 0.41.0 Numba docs, update `latest` link
* [x] Send announcement email
* [x] Post link to twitter

## On completion
* [x] Contact distribution team to start build out for main channels
