### ISSUE TITLE
Numba 0.42RC checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#3600]
## llvmlite
* [x] Merge pending PRs
    * [x] numba/llvmlite#430 (build lld in llvmdev)
    * [ ] ~~numba/llvmlite#419 (wrap lld in Python)~~ (Defer until v0.28.0, needs rebase and work)
* [x] Verify docs all refer to LLVM 7
* [x] update changelog
* [x] tag 0.27.0rc1, build on buildfarm
* [x] verify conda packages uploaded to Anaconda Cloud
* [x] move packages from dev to main label

## numba

* [x] Merge pending PRs
  * [x] numba#3392 (gdb in nopython)
  * [X] ~~numba#3505 (non intp ints in np.* allocators)~~ (hold to 0.43 for further review)
  * [x] numba#3520 (fix `@stencil` ignoring cval)
  * [x] numba#3549 (parallelaccelerator caching improvements)
  * [x] numba#3558 (fix array analysis for inplace operators)
  * [x] numba#3567 (fix unifying literals in namedtuple)
  * [x] ~~numba#3594 (change `@stencil` docs)~~ (bumping to next release)
  * [x] numba#3596 (fix array analysis of global namedtuples)
  * [x] numba#3597 (warn users if thread backend init unsafe)
* [x] Update install docs to describe ARMv7 install (#3609)
* [x] Check docs for updating references to LLVM 7
* [x] Merge changelog (#3608)
* [x] switch build farm into release mode
* [x] Create 0.42 branch
* [x] Tag empty commit for 0.42.0rc1 on branch
* [x] Build conda packages on build farm
* [x] Verify conda packages uploaded to Anaconda Cloud
* [x] switch build farm into dev mode
* [x] Send RC announcement email
* [x] Post link to twitter

**Comment by seibert** [comment]
switching build farm to dev mode is pending completion of the armv7l packages.
