### ISSUE TITLE
Numba 0.42 final release checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#3626]
## llvmlite

* [x] verify llvm 7 and llvmlite build on manylinux1
* [x] Tag 0.27.0
* [x] switch build farm to release mode
* [x] Build conda packages on build farm (tag will not automatically trigger new build)
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels
   - Python [2.7, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI

## numba
* [x] Cherry pick #3617 to release branch
* [x] Review & merge https://github.com/numba/numba/pull/3631 ~Update release notes (on master) to include #3616 and #3617~
* [x] Cherry pick release note update #3631 to release branch
* [x] Tag `0.42.0` on branch
* [x] Verify build farm in release mode
* [x] Build conda packages on build farm
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Switch build farm to development mode
* [x] Build wheels
   - Python [2.7, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI
* [x] Upload 0.42.0 Numba docs, update `latest` link
* [x] Send announcement email
* [x] Post link to twitter

## On completion
* [x] Contact distribution team to start build out for main channels

**Comment by seibert** [comment]
Release is done!
