### ISSUE TITLE
Numba 0.43 RC checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#3833]
## llvmlite
* [x] Merge pending PRs? (no more to merge this release)
* [x] update changelog (https://github.com/numba/llvmlite/pull/465)
* [x] branch master to 0.28,
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] tag 0.28.0rc1 on branch, build on buildfarm
* [x] verify conda packages uploaded to Anaconda Cloud

## numba

* [x] Merge pending PRs
  * [x] numba#3832 (handle CUDA search path of single string)
  * [x] numba#3830 (Getitem should not return optional type)
  * [x] numba#3829 (docs for typed dict)
  * [x] numba#3792 (fix non-module used as module of function)
  * [x] numba#3782 (raise typing error on yield optional value)
  * [x] numba#3725 (fix invalid removal of dead empty list)
* [x] update changelog (#3837)
* [x] Create 0.43 branch
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
  - Didn't seem to work, will need to move packages to main below
  - (thanks, @stuartarchibald noted, bug found, fix needed on farm)
* [x] Tag empty commit for 0.43.0rc1 on branch
* [x] Build conda packages on build farm (*in progress*)
* [x] Verify conda packages uploaded to Anaconda Cloud
* [x] Move packages to main label (because of issue above)
* [x] Send RC announcement email
* [x] Post link to twitter

**Comment by seibert** [comment]
closing now that RC has been posted

**Comment by seibert** [comment]
For next release: be sure to add steps for tagging master with the next dev release tag right after branching.
