### ISSUE TITLE
Numba 0.43.0 release checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#3858]
## llvmlite

* [x] Tag 0.28.0 on 0.28 branch
* [x] Build conda packages on build farm (tag will not automatically trigger new build)
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels
   - Python [2.7, 3.5, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI

## numba
* [x] Review and merge #3856 to master
* [x] Cherry pick #3856 to `release0.43` branch
* [x] Tag `0.43.0` on branch
* [x] Build conda packages on build farm
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels
   - Python [2.7, 3.5, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI
* [x] Upload 0.43.0 Numba docs, update `latest` link
* [x] Send announcement email
* [x] Post link to twitter

## On completion
* [x] Contact distribution team to start build out for main channels

**Comment by seibert** [comment]
Release finished!
