### ISSUE TITLE
Numba 0.43.1 RC checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#3889]
## llvmlite
* no changes needed

## numba

* [x] Merge pending PRs
  * [x] #3883 (branch prune fix for object mode fallback)
  * [x] #3850 (refactor np interp)
  * [x] #3826 (full NumPy 116 support)
* [x] update changelog
* [x] cherry pick commits to release0.43 branch
* [x] Tag commit for 0.43.1rc1 on branch
* [x] Build conda packages on build farm
* [x] Verify conda packages uploaded to Anaconda Cloud
* [x] Send RC announcement email
* [x] Post link to twitter
