### ISSUE TITLE
Numba release 0.44 release checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#4102]
## llvmlite

* [x] Tag 0.29.0 on 0.29 branch
* [x] Build conda packages on build farm (tag will not automatically trigger new build)
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels
   - Python [2.7, 3.5, 3.6, 3.7] x [linux32 (done), linux64 (done), win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI

## numba
* [x] Bump minimum required llvmlite in requirements.txt to 0.29.0 (not dev) as per [this note](https://github.com/numba/numba/issues/4106#issuecomment-494835154)
* [x] Tag `0.44.0` on branch
* [x] Build conda packages on build farm
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels
   - Python [2.7, 3.5, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI
* [x] Upload 0.44.0 Numba docs, update `latest` link
* [x] Send announcement email
* [x] Post link to twitter

## On completion
* [x] Contact distribution team to start build out for main channels

**Comment by seibert** [comment]
FYI, this is for final release.  Need to do #4106 first.  :)

**Comment by dsevero** [comment]
Maybe require `llvmlite>0.29.0dev0` as mentioned in https://github.com/numba/numba/issues/4106#issuecomment-494835154

**Comment by seibert** [comment]
OK, release done!

**Comment by dsevero** [comment]
```bash
> poetry update -vv
  [...]
  - Updating llvmlite (0.28.0 -> 0.29.0)
  - Updating numba (0.43.1 -> 0.44.0)
  [...]
  - Removing enum34 (1.1.6)
```

Awesome! Thanks!
