### ISSUE TITLE
Numba 0.44 RC1 checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#4106]
## llvmlite
* [x] Merge pending PRs?
* [x] update changelog
* [x] branch master to 0.29
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] tag 0.29.0rc1 on branch, build on buildfarm
* [x] verify conda packages uploaded to Anaconda Cloud

## numba

* [x] Merge pending PRs
  * [x] numba#4105 (remove info about CUDA ENVVAR potential replacement) 
  * [x] numba#4104 (pep 508 env markers)
  * [x] numba#4100 (fix alignment check on 32-bit)
  * [x] numba#3899 (Support for np.quantile and np.nanquantile)
* [x] update changelog
* [x] Create 0.44 branch
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] Tag empty commit for 0.44.0rc1 on branch
* [x] Build conda packages on build farm
* [x] Verify conda packages uploaded to Anaconda Cloud
* [x] Send RC announcement email
* [x] Post link to twitter

**Comment by dsevero** [comment]
Since `llvmlite<=0.29.0dev0` has the `enum34` issue (see https://github.com/numba/llvmlite/pull/483), shouldn't we require `llvmlite>0.29.0dev0` (strictly larger than) [here](https://github.com/numba/numba/blob/master/setup.py#L308)?

**Comment by seibert** [comment]
We don't usually post RC wheels (only the final release), so practically this won't matter, but this is a good catch to make sure our final release requires >= 0.29.0 (final, not dev)

**Comment by dsevero** [comment]
Good point. I added it to the 0.44 checklist as a suggestion.

**Comment by seibert** [comment]
RC done.  On to the final release next week!
