### ISSUE TITLE
Numba 0.44.1 patch release checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#4171]
## numba
* [x] Resolve regressions on master:
  * [x] PR #4165 (fixes #4164 regression in NUMBAPRO variable)
  * [x] PR #4172 (fixes #4163 branch pruning regression)
  * [x] PR #4183 (fixes #4156 memory leak)
* [x] Update changelog on master
* [x] Cherry pick PR commits and changelog to `release0.44` branch
* [x] Tag `0.44.1` on branch
* [x] Build conda packages on build farm (some win-64 straggler packages, but done enough to announce)
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels
   - Python [2.7, 3.5, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI
* [x] Upload 0.44.1 Numba docs, update `latest` link
* [x] Send announcement email
* [x] Post link to twitter

## On completion
* [x] Contact distribution team to start build out for main channels
