### ISSUE TITLE
Numba 0.45.0RC1 checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#4298]
## llvmlite
* Nothing to do!  No changes to llvmlite this development cycle.

## numba
* [x] Verify master is building again on internal CI
* [x] Review and merge changelog (numba#4297)
* [x] Create 0.45 branch
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] Tag empty commit for 0.45.0rc1 on branch
* [x] Build conda packages on build farm
* [x] Verify conda packages uploaded to Anaconda Cloud
* [x] Send RC announcement email
* [x] Post link to twitter

Post RC:
* [x] Tag 0.46.0dev0 to start new cycle
