### ISSUE TITLE
Numba 0.45.0 release checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#4329]
## llvmlite
* Nothing to do!  No changes to llvmlite this development cycle.

## numba

* [x] Cherry-pick
    * [x] #4317
    * [x] #4328
    * [x] #4318
    * [x] #4311
* [x] Start build on release0.45 to verify the cherrypicked PRs.
    * [x] Check ^ build
* [x] Merge https://github.com/numba/numba/pull/4334
* [x] Cherrypick https://github.com/numba/numba/pull/4334
* [x] Tag 0.45.0 on branch
* [x] Build conda packages on build farm
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels
* [x] Python [2.7, 3.5, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI
* [x] Upload 0.45.0 Numba docs, update latest link
* [x] Send announcement email
* [x] Post link to twitter

**Comment by seibert** [comment]
Release done!
