### ISSUE TITLE
Meta issue: np1.17 fixes

### ISSUE THREAD

**Issue by sklam** [numba/numba#4358]
- [x] isnan, isinf, isfinite ufuncs has new specialized loops for ints (https://github.com/numba/numba/pull/4357)
- [x] `numpy.random.ranf` not longer alias to `random_sample`. (https://github.com/numba/numba/pull/4371)
   - causes test `numba.tests.test_array_analysis.TestArrayAnalysis.test_numpy_calls` to fail.
- [x] changes in `np.interp` can now return `inf` instead of `nan` for same cases. (https://github.com/numba/numba/pull/4363)
   - causes test `numba.tests.test_np_functions.TestNPFunctions.test_interp_complex_stress_tests` to fail.

**Comment by seibert** [comment]
All PRs have been merged
