### ISSUE TITLE
Numba 0.45.1 checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#4381]
## llvmlite
* Nothing to do!  No changes to llvmlite for patch release

## numba

* [x] Cherry-pick PRs from [0.45.1 milestone](https://github.com/numba/numba/milestone/29?closed=1)
    * [x] #4350 (process level locks)
    * [x] #4325 (accept scalar/0-d arrays)
    * [x] https://github.com/numba/numba/pull/4338 (parfors reduction variable not deleted)
    * [x] #4354 (fix #4352 exception on interpreter exit)
    * [x] #4357 (np1.17 isnan, etc)
    * [x] #4363 (np1.17 interp handling of nan)
    * [x] #4371 (np1.17 random function aliasing)
* [x] Changelog
    * [x] Changelog update PR (#4383)
    * [x] Merge changelog to master
    * [x] Cherry pick to release0.45
* [x] Tag 0.45.0 on branch
* [x] Build conda packages on build farm
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Build wheels: Python [2.7, 3.5, 3.6, 3.7] x [linux32, linux64, win32, win64, macOS]
* [x] Upload wheels to PyPI
* [x] Upload sdist to PyPI
* [x] Upload 0.45.1 Numba docs, update latest link
* [x] Send announcement email
* [x] Post link to twitter

**Comment by seibert** [comment]
release done!
