### ISSUE TITLE
Numba 0.46.0RC1 checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#4622]
## llvmlite
* [x] Merge pending PRs?
* [x] update changelog (review https://github.com/numba/llvmlite/pull/517)
* [x] branch master to 0.30
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] tag 0.30.0rc1 on branch, build on buildfarm
* [x] verify conda packages uploaded to Anaconda Cloud

## numba

* [x] Merge pending PRs
    * [ ] https://github.com/numba/numba/pull/4210 if done
    * [ ] https://github.com/numba/numba/pull/4418 if done
    * [x] https://github.com/numba/numba/pull/4472
    * [x] https://github.com/numba/numba/pull/4510
    * [x] https://github.com/numba/numba/pull/4520 if done
    * [ ] https://github.com/numba/numba/pull/4536 if done
    * [x] https://github.com/numba/numba/pull/4556
    * [x] https://github.com/numba/numba/pull/4568
    * ~https://github.com/numba/numba/pull/4578 if done~
    * [x] https://github.com/numba/numba/pull/4595 if done
    * [x] https://github.com/numba/numba/pull/4601
    * [x] https://github.com/numba/numba/pull/4606 if done
    * [x] https://github.com/numba/numba/pull/4607
    * [x] https://github.com/numba/numba/pull/4609
    * [x] https://github.com/numba/numba/pull/4614
    * [x] https://github.com/numba/numba/pull/4619

* [x] Create release branch
* [x] Start build on release0.46.
    * [ ] Check ^ build
* [x] Merge "#CHANGE_LOG_PR"
* [x] Cherrypick "#CHANGE_LOG_PR
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [ x] Tag 0.46.0rc1 on branch
* [x] Build conda packages on build farm
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Send announcement email
* [ ] Post link to twitter
