### ISSUE TITLE
Numba 0.46.0 final checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#4679]
## llvmlite
* [x] tag 0.30.0 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels [linux-32, linux-64, osx-64, win-32, win-64] * [Python 2.7, 3.5, 3.6, 3.7]
* [x] verify conda packages uploaded to Anaconda Cloud
* [x] upload wheels and sdist to PyPI
* [x] Prep for 0.31.0dev0 https://github.com/numba/llvmlite/pull/520

## numba

* [x] ~cherry pick #4675~ merge #4680 to release branch
* [x] update changelog with #4675 and large warning about incompatibility with Numba's device arrays and CuPy until next CuPy release.  (Note that Numba CUDA kernels will work with older CuPy device arrays.) https://github.com/numba/numba/pull/4682
* [x] cherry pick changelog update to release branch
* [x] tag 0.46.0 on release branch
* [x] add release notebook to numba-examples repo
* [x] build conda packages on buildfarm
* [x] build wheels
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] upload 0.46.0 docs, update "latest" link
* [x] Send announcement email
* [x] Post link to twitter
