### ISSUE TITLE
Numba 0.47.0rc1 Checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#4992]
## llvmlite
* [x] update changelog
* [x] branch master to 0.31
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] tag 0.31.0rc1 on branch
* [x] build on buildfarm (remember to check the "upload" box)
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel

Post RC:
* [x] Tag 0.32.0dev0 to start new cycle

## numba
* [x] Merge remaining PRs in https://github.com/numba/numba/milestone/30
* [x] Write, review and merge changelog ()
* [x] Create 0.47 branch
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] Tag .label commit for 0.47.0rc1 on branch
* [x] Build conda packages on build farm (remember to check the "upload" box)
* [x] Verify conda packages uploaded to Anaconda Cloud and in main channel
* [x] Send RC announcement email
* [x] Post link to twitter

Post RC:
* [x] Tag 0.48.0dev0 to start new cycle

**Comment by bryevdv** [comment]
@seibert did you mean *"Tag 0.4**8**.0dev0 to start new cycle"*?  Is there an ETA for this release (and really: conda packages on main)

**Comment by stuartarchibald** [comment]
@bryevdv thanks for spotting that! I've edited the ticket.

**Comment by seibert** [comment]
We are tagging the RC1 and building test packages in the numba channel today.  Around the new year we'll tag the final release and then I expect the Anaconda Distribution team will work on it in their first sprint in January.

**Comment by seibert** [comment]
note that rc1 packages for python 3.8 + osx-64 are not available due to a test failure with pycc when linking.  We will have to decide whether to skip that test or find a workaround before the final release.

**Comment by seibert** [comment]
@bryevdv: Numba 0.47.0 packages are now on the main channel for Python 2.7, 3.6, and 3.7.  It looks like python 3.8 builds might be still pending.

**Comment by seibert** [comment]
Python 3.8 packages are now on the main channel as well.
