### ISSUE TITLE
Numba 0.47.0 final checklist

### ISSUE THREAD

**Issue by seibert** [numba/numba#5020]
## llvmlite
* [x] annotated tag 0.31.0 on release branch
* [x] build conda packages on buildfarm 
* [x] build wheels [linux-32, linux-64, osx-64, win-32, win-64] * [Python 2.7, 3.5, 3.6, 3.7, 3.8]
* [x] verify conda packages uploaded to Anaconda Cloud
* [x] upload wheels and sdist to PyPI

## numba

* [x] cherry-pick PRs to release0.47 branch
  - #5019 - skip pycc on Py3.8 + macOS
  - #5018 - fix #5011
  - https://github.com/numba/numba/pull/5021 changelog update
* [x] update changelog
* [x] cherry pick changelog update to release branch
* [x] annotated tag 0.47.0 on release branch
* [x] add release notebook to numba-examples repo
* [x] build conda packages on buildfarm
* [x] build wheels (2.7, 3.5, 3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] upload 0.47.0 docs, update "latest" link
* [x] Send announcement email
* [x] Send email about Q1 2020 dev plans (dropping packages, 0.48 quick release and 0.49 refactoring release)
* [x] Post link to twitter

**Comment by seibert** [comment]
All done.

**Comment by bryevdv** [comment]
what's the usual turnaround to appear in defaults?

**Comment by seibert** [comment]
We've asked to be put into the 2 week package build sprint that starts today, so hopefully < 2 weeks.
