### ISSUE TITLE
Numba 0.48.0rc1 Checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5089]
## llvmlite
* No changes, do nothing.

Post RC:
* No changes, do nothing.

## numba
* [x] Merge remaining PRs in https://github.com/numba/numba/milestone/32
* [x] Update deprecation notices and merge PR https://github.com/numba/numba/pull/5090
* [x] Write, review and merge changelog () https://github.com/numba/numba/pull/5091
* [x] Create 0.48 branch
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] Annotated tag .label commit for 0.48.0rc1 on branch
* [x] Build conda packages on build farm (remember to check the "upload" box)
* [x] Verify conda packages uploaded to Anaconda Cloud and in main channel
* [x] Send RC announcement email
* ~[ ] Post link to twitter~ (too late; skipping)

Post RC:
* [x] Tag 0.49.0dev0 to start new cycle
