### ISSUE TITLE
Checklist for 0.48.0 release

### ISSUE THREAD

**Issue by sklam** [numba/numba#5145]
## llvmlite

* nothing to do

## numba

* [x] cherry-pick PRs to release0.48 branch
  - https://github.com/numba/numba/pull/5092
* [x] update changelog
* [x] cherry pick changelog update to release branch (https://github.com/numba/numba/pull/5147)
* [x] annotated tag 0.48.0 on release branch
* [x] build conda packages on buildfarm (buildno `numba_102`)
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] upload 0.48.0 docs, update "latest" link
* [x] Send announcement email
* [x] Post link to twitter

**Comment by seibert** [comment]
remember you can skip Python 2.7 and 3.5 for this release.

**Comment by sklam** [comment]
good catch. updated
