### ISSUE TITLE
Numba 0.49.0rc1 Checklist 

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5410]
## llvmlite
* [x] update changelog
* [x] branch master to 0.32
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] tag 0.32.0rc1 on branch
* [x] build on buildfarm (remember to check the "upload" box)
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel

Post RC:
* [x] Tag 0.33.0dev0 to start new cycle

## numba
* [x] Merge remaining PRs in https://github.com/numba/numba/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Numba+0.49+RC%22
* [x] Write, review and merge changelog ()
* [x] Create 0.49 branch
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] Annotated tag .label commit for 0.49.0rc1 on branch
* [x] Build conda packages on build farm (remember to check the "upload" box)
* [x] Verify conda packages uploaded to Anaconda Cloud and in main channel
* [x] Send RC announcement email
* [x] Post link to twitter

Post RC:
* [x] Tag 0.50.0dev0 to start new cycle
