### ISSUE TITLE
release 0.49.0rc2 checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#5516]
## numba
* [x] Cherrypick PRs 
    * [x] #5423 
    * [x] #5450 
    * [x] #5453 
    * [x] #5454 
    * [x] #5455
    * [x] #5480 
    * [x] #5485 
    * [x] #5488 
    * [x] #5489 
    * [x] #5495
    * [x] #5498 
    * [x] #5527
    * [x] #5529
    * [x] #5532
  
* [x] update changelog (https://github.com/numba/numba/pull/5538)
* [x] Annotated tag .label commit for 0.49.0rc2 on branch
* [x] Build conda packages on build farm (remember to check the "upload" box)
* [x] Verify conda packages uploaded to Anaconda Cloud and in main channel
* [x] Send RC announcement email
* [x] Post link to twitter
