### ISSUE TITLE
Numba 0.49.0 Checklist 

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5564]
## llvmlite
* [x] merge https://github.com/numba/llvmlite/pull/577
* [x] cherrypick https://github.com/numba/llvmlite/pull/577
* [x] update changelog https://github.com/numba/llvmlite/pull/576
* [x] Annotated tag 0.32.0 on branch
* [x] build on buildfarm (remember to check the "upload" box)
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel

## numba
* [x] Cherry-pick PRs:
  * [x] https://github.com/numba/numba/pull/5436
  * [x] https://github.com/numba/numba/pull/5457
  * [x] https://github.com/numba/numba/pull/5459
  * [x] https://github.com/numba/numba/pull/5505
  * [x] https://github.com/numba/numba/pull/5519
  * [x] https://github.com/numba/numba/pull/5542
  * [x] https://github.com/numba/numba/pull/5548
  * [x] https://github.com/numba/numba/pull/5555
  * [x] https://github.com/numba/numba/pull/5557
  * [x] #5568
* [x] Update changelog (#5567)
* [x] cherry pick changelog (#5567) to release branch 
* [x] sort out new patches
    * [x] cherrypick:
      * [x] https://github.com/numba/numba/pull/5569
    * [x] merge to release branch:
      * [x] https://github.com/numba/numba/pull/5571
    * [x] erase from history on release branch:
      * [x] #5568
* [x] update changelog for the above edits (#5574) and merge
* [x] cherry-pick changelog update(#5574) to release branch
* [x] annotated tag 0.49.0 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] upload 0.49.0 docs, update "latest" link
* [x] Review, merge and check execution of release notebook https://github.com/numba/numba-examples/pull/14
* [x] Send announcement email
* [x] Post link to twitter
