### ISSUE TITLE
Numba 0.49.1RC1 checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5622]
## llvmlite
* [x] consider these:
  * [x] https://github.com/numba/llvmlite/pull/580
  * [x] https://github.com/numba/llvmlite/pull/581
  * [x] https://github.com/numba/llvmlite/pull/582
* [x] cherrypicks:
  * [x] 580
  * [x] 581
  * [x] 582
* [ ] update changelog (https://github.com/numba/llvmlite/pull/585)
* [ ] Annotated tag 0.32.1 on branch
* [ ] build conda packages on buildfarm (remember to check the "upload" box)
* [ ] build wheels (3.6, 3.7, 3.8)
* [ ] upload wheels and sdist to PyPI
* [ ] verify conda packages uploaded to Anaconda Cloud and in main channel

## numba
* [x] Consider these:
  * PR #5652: Pin to sphinx=2.4.4 to avoid problem with C declaration
  * PR #5651: Fix some SSA issues
  * PR #5648: Unset the memory manager after EMM Plugin tests
  * PR #5638: Make literal_unroll function work as a freevar.
  * PR #5630: Fix #5570. Incorrect race variable detection due to SSA naming.
  * PR #5629: Fixes naming error in array_exprs
  * PR #5627: Fixes #5623, SSA local def scan based on invalid equality
    assumption.
  * PR #5626: Fix unifying undefined first class function types issue
  * PR #5624: Fix erroneous rewrite of predicate to bit const on prune.
  * PR #5614: Fix invalid type in resolve for comparison expr in parfors.
  * PR #5592: Fixes #5583 Remove references to cffi_support from docs and examples
  * PR #5587: Fixed #5586 Threading Implementation Typos
  * Wheels on windows missing runtime lib: https://github.com/numba/numba/issues/5600
* [x] Cherry-pick PRs:
    - [x] #5652
    - [x] #5651
    - [x] #5648
    - [x] #5638
    - [x] #5630
    - [x] #5629
    - [x] #5627
    - [x] #5624
    - [x] #5614
    - [x] #5592
    - [x] #5587
    - [x] #5658 (includes #5626)
    - [x] #5657

* [x] Update changelog (https://github.com/numba/numba/pull/5657)
* [x] cherry pick changelog (Issue # TBC) to release branch 
* [x] annotated tag 0.49.1 on release branch
* [x] build conda packages on buildfarm  (remember to check the "upload" box)
* [x] build wheels (3.6, 3.7, 3.8)
* [x] Check linkage on wheels with `lief`
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] upload 0.49.1 docs, update "latest" link
* [x] Send announcement email
* [x] Post link to twitter
