### ISSUE TITLE
Numba 0.49.1 checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5683]
## llvmlite
* [x] Check code changes on branch are correct (#580. #581, #582, #585).
* [x] Annotated tag 0.32.1 on branch
* [x] build conda packages on buildfarm (remember to check the "upload" box)
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel

## numba
* [x] Cherry-pick PRs:
    - [x] #5669
    - [x] #5676
* [x] Update changelog (https://github.com/numba/numba/pull/5682)
* [x] cherry pick changelog (Issue #5682) to release branch 
* [x] annotated tag 0.49.1 on release branch
* [x] build conda packages on buildfarm  (remember to check the "upload" box)
* [x] build wheels (3.6, 3.7, 3.8)
* [x] Check linkage on wheels with `lief`
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] upload 0.49.1 docs, update "latest" link
* [x] Send announcement email
* [x] Post link to twitter

**Comment by esc** [comment]
I updated the checklist to include pinging the distro team.
