### ISSUE TITLE
Numba 0.50.0rc1 Checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5794]
## llvmlite
* [x] update changelog
* [x] branch master to 0.33
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] tag 0.33.0rc1 on branch
* [x] build conda packages on buildfarm (remember to check the "upload" box)
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel

Post RC:
* [x] Tag 0.34.0dev0 to start new cycle

## numba
* [x] Merge remaining PRs in https://github.com/numba/numba/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Numba+0.50+RC%22
* [x] Write, review and merge changelog (TBC)
* [x] Create 0.50 branch
* [x] commit to branch to set .label to `main` (see https://github.com/numba/llvmlite/pull/451/files for label use)
* [x] Annotated tag .label commit for 0.50.0rc1 on branch
* [x] build conda packages on buildfarm  (remember to check the "upload" box)
* [x] Verify conda packages uploaded to Anaconda Cloud and in main channel
* [x] build wheels (3.6, 3.7, 3.8)
* [x] Check linkage on wheels with `lief`
* [x] upload wheels and sdist to PyPI
* [x] Send RC announcement email
* [x] Post link to twitter

Post RC:
* [x] Tag 0.51.0dev0 to start new cycle
