### ISSUE TITLE
 Numba 0.50.0 Checklist 

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5843]
## llvmlite
* [x] Annotated tag 0.33.0 on branch
* [x] build on buildfarm (remember to check the "upload" box)
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI

## numba
* [x] Merge to master:
  * [x] https://github.com/numba/numba/pull/5812 (inliner IR mutation fix)
  * [x] https://github.com/numba/numba/pull/5833 (error message fix)
  * [x] #5842 (change log update)
* [x] Cherry-pick PRs:
  * [x] https://github.com/numba/numba/pull/5812 (inliner IR mutation fix)
  * [x] https://github.com/numba/numba/pull/5833 (error message fix)
* [x] Cherry pick changelog update (#5842) to release branch 
* [x] annotated tag 0.50.0 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] upload 0.50.0 docs, update "latest" link
* [x] Review, merge and check execution of release notebook [TODO] (https://github.com/numba/numba-examples/pull/18)
* [x] Send announcement email
* [x] Post link to twitter

Post release:
* [x] Ping Anaconda distro team for build out.
