### ISSUE TITLE
Release 0.50.1 checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#5917]
## numba
* [x] Merge to master:
    - [x] https://github.com/numba/numba/pull/5889
    - [x] https://github.com/numba/numba/pull/5912
    - [x] https://github.com/numba/numba/pull/5918
* [x] Cherry-pick PRs:
    - [x] https://github.com/numba/numba/pull/5861
    - [x] https://github.com/numba/numba/pull/5884
    - [x] https://github.com/numba/numba/pull/5889
    - [x] https://github.com/numba/numba/pull/5912
    - [x] https://github.com/numba/numba/pull/5876
    - [x] https://github.com/numba/numba/pull/5918
* [x] merge change log changes
    - [x] https://github.com/numba/numba/pull/5913
    - [x] https://github.com/numba/numba/pull/5919
* [x] annotated tag 0.50.1 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] upload 0.50.1 docs, update "latest" link
* [x] Send announcement email
* [x] Post link to twitter

Post release:
* [x] Ping Anaconda distro team for build out.
