### ISSUE TITLE
Release 0.51.0RC1 / 0.34.0RC1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#6003]
## llvmlite

* [x] Merge to master:
    - [x] https://github.com/numba/llvmlite/pull/599
    - [x] https://github.com/numba/llvmlite/pull/602
    - [x] https://github.com/numba/llvmlite/pull/598
* [x] merge change log changes
    - [x] - https://github.com/numba/llvmlite/pull/610
* [x] Create 0.34 release branch
* [x] Annotated tag 0.34.0rc1 on branch
* [x] build on buildfarm (remember to check the "upload" box)
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel

Post RC:
* [x] Tag 0.35.0dev0 to start new cycle

## numba 0.51.0
* [x] Merge to master:
    - [x] - https://github.com/numba/numba/pull/5962
    - [x] - https://github.com/numba/numba/pull/6078
    - [x] - https://github.com/numba/numba/pull/6080
    - [x] - https://github.com/numba/numba/pull/6081
    - [x] - https://github.com/numba/numba/pull/6083
* [x] merge change log changes
    - [x] - https://github.com/numba/numba/pull/6084
* [x] Copy `icc_rt` from intel channel to `numba/label/main`
* [x] Create 0.51 release branch
* [x] annotated tag 0.51.0rc1 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Send RC announcement email / post announcement to discourse group
* [x] Post link to twitter

Post RC:

* [x] Tag 0.52.0dev0 to start new cycle

Notes:
* LLVM in llvmlite is being upgraded to 10.0.1 for all platforms except `aarch64` which stay at 9.0.1. This means all released `llvmlite` packages will carry aLLVM 10.0.1 except for the one for `aarch64` which will carry a 9.0.1.

**Comment by esc** [comment]
https://twitter.com/numba_jit/status/1291452216927227906

**Comment by seibert** [comment]
Thanks!
