### ISSUE TITLE
Release 0.51.0 checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#6119]
## llvmlite

* [x] check on BFID: `llvmlite_46` for release branch build
* [x] annotated tag v0.34.0 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud (to `numba/label/main`)

## numba
* [x] Merge to master:
    - [x] https://github.com/numba/numba/pull/6087
    - [x] https://github.com/numba/numba/pull/6089
    - [x] https://github.com/numba/numba/pull/6097
    - [x] https://github.com/numba/numba/pull/6099
    - [x] https://github.com/numba/numba/pull/6101
    - [x] https://github.com/numba/numba/pull/6107
    - [x] https://github.com/numba/numba/pull/6111
    - [x] https://github.com/numba/numba/pull/6109
    - [x] https://github.com/numba/numba/pull/6116
    - [x] https://github.com/numba/numba/pull/6123
* [x] Cherry-pick PRs:
    - [x] https://github.com/numba/numba/pull/6087
    - [x] https://github.com/numba/numba/pull/6089
    - [x] https://github.com/numba/numba/pull/6097
    - [x] https://github.com/numba/numba/pull/6099
    - [x] https://github.com/numba/numba/pull/6101
    - [x] https://github.com/numba/numba/pull/6107
    - [x] https://github.com/numba/numba/pull/6111
    - [x] https://github.com/numba/numba/pull/6109
    - [x] https://github.com/numba/numba/pull/6116
    - [x] https://github.com/numba/numba/pull/6123
* [x] merge change log changes
    - [x] https://github.com/numba/numba/pull/6117
    - [x] https://github.com/numba/numba/pull/6124 (and cherry pick in)
* [x] merge llvmlite version bump  (https://github.com/numba/numba/pull/6120) BFID: `numba_202`
* [x] annotated tag 0.51.0 on release branch
* [x] build conda packages on buildfarm (`numba_203`)
* [x] build wheels (3.6, 3.7, 3.8) (`numba_wheel_22`)
* [x] decide on how to fix the wheel problem
    * [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] upload 0.51.0 docs, update "latest" link
* [x] Send announcement email
* [x] Post link to twitter

Post release:
* [x] Ping Anaconda distro team for build out.

**Comment by gmarkall** [comment]
It seems that this commit: https://github.com/numba/numba/commit/e203c9d8c00590882fb50a9f0e70d09f255bb4ab causes Numba to go into an infinite loop (or at least recompile the same thing a lot needlessly) - this seems like it may be a bit of a blocker - I'm investigating a bit more now.

**Comment by gmarkall** [comment]
Opened #6121 to track the issue.

**Comment by stuartarchibald** [comment]
Thanks all, closing!

**Comment by esc** [comment]
🙌
