### ISSUE TITLE
Release 0.51.1 checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6172]
## numba
* [x] Merge to master:
  - [x] No PRs pending
* [x] Cherry-pick PRs:
    - [x] https://github.com/numba/numba/pull/6141
    - [x] https://github.com/numba/numba/pull/6146
    - [x] https://github.com/numba/numba/pull/6147
    - [x] https://github.com/numba/numba/pull/6153
    - [x] https://github.com/numba/numba/pull/6168
* [x] merge change log changes
    - [x] https://github.com/numba/numba/pull/6171
* [x] Cherry-pick change log:
   - [x] https://github.com/numba/numba/pull/6171
* [x] annotated tag 0.51.1 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] upload 0.51.1 docs, update "latest" link (is this now automatic since ReadTheDocs?)
* [x] Send announcement 
* [x] Post link to twitter

Post release:
* [x] Ping Anaconda distro team for build out.

**Comment by esc** [comment]
🎉
