### ISSUE TITLE
Release 0.51.2 checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#6205]
## numba
* [x] Merge to master:
    - [x] https://github.com/numba/numba/pull/6195
* [x] Cherry-pick PRs:
    - [x] https://github.com/numba/numba/pull/6195
* [x] merge change log changes
    - [x] https://github.com/numba/numba/pull/6201
* [x] Cherry-pick change log:
    - [x] https://github.com/numba/numba/pull/6201
* [x] annotated tag 0.51.2 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] Verify ReadTheDocs build
* [x] Send announcement 
* [x] Post link to twitter

Post release:
* [x] Ping Anaconda distro team for build out.
