### ISSUE TITLE
Numba 0.52.0RC1 / llvmlite 0.35.0RC1 checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#6332]
## llvmlite

* [x] Merge to `master` (when approved):
    - [x] https://github.com/numba/llvmlite/pull/626
    - [x] https://github.com/numba/llvmlite/pull/627
* [x] merge change log changes (https://github.com/numba/llvmlite/pull/643)
* [x] Create 0.35 release branch
* [x] Annotated tag 0.35.0rc1 on branch
* [x] build on buildfarm (remember to check the "upload" box)
* [ ] build wheels (3.6, 3.7, 3.8)
* [ ] upload wheels and sdist to PyPI
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel

Post RC:
* [ ] Tag 0.36.0dev0 on `master` to start new cycle

## numba 0.52.0

* [x] Merge to master:
    - [x] - https://github.com/numba/numba/milestone/40
* [x] merge change log changes
    - [x] - https://github.com/numba/numba/pull/6365
* [x] Create 0.52 release branch
* [x] annotated tag 0.52.0rc1 on release branch
* [x] build conda packages on buildfarm
* [ ] build wheels (3.6, 3.7, 3.8)
* [ ] upload wheels and sdist to PyPI
* [ ] Verify packages uploaded to Anaconda Cloud
* [ ] Send RC announcement email / post announcement to discourse group
* [ ] Post link to twitter

Post RC:

* [ ] Tag 0.53.0dev0 to start new cycle

**Comment by stuartarchibald** [comment]
Release announcement: https://numba.discourse.group/t/numba-0-52-0-and-llvmlite-0-35-0-release-candidates/284

0.52.0RC2 outstanding tickets are here: https://github.com/numba/numba/milestone/48
