### ISSUE TITLE
Numba 0.53.0RC1 / llvmlite 0.36.0RC1 checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6684]
## llvmlite

* [x] Merge to `master` (when approved):
    -  None?
* [x] merge change log changes (https://github.com/numba/llvmlite/pull/696)
* [x] Create 0.36 release branch
* [x] Annotated tag v0.36.0rc1 on branch
* [x] build on buildfarm (remember to check the "upload" box)
* [x] build wheels (3.6, 3.7, 3.8, 3.9) (remember to check the "upload" box)
* [x] move conda packages from `numba/label/dev` to `numba/label/main`
* [x] upload wheels and sdist to PyPI
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel
* [x] verify wheels for all platforms arrived on PyPi

Post RC:
* [x] Tag v0.37.0dev0 on `master` to start new cycle

## numba 0.53.0

* [x] Merge to master:
    - [x] add classifier for python3.9
    - [x] - https://github.com/numba/numba/milestone/44
* [x] merge change log changes
    - [x] - https://github.com/numba/numba/pull/6683
* [x] Create 0.53 release branch
* [x] pin llvmlite to `>=0.36.0rc1,<0.37.0`
* [x] annotated tag 0.53.0rc1 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8, 3.9)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud
* [x] verify wheels for all platforms arrived on PyPi
* [x] Send RC announcement email / post announcement to discourse group
* [x] Post link to twitter

Post RC:

* [x] Tag 0.54.0dev0 to start new cycle
* [x] update llvmlite dependency spec to match next version (https://github.com/numba/numba/pull/6750)

**Comment by esc** [comment]
Conda packages, wheels and sdists are now available for this RC. See discourse: https://numba.discourse.group/t/numba-0-53-0-and-llvmlite-0-36-0-release-candidates/504 for details on how to install.

**Comment by esc** [comment]
🎉
