### ISSUE TITLE
Numba 0.53.0rc2 checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#6764]
## llvmlite

* [x] merge & cherrypick https://github.com/numba/llvmlite/milestone/11
* [x] merge change log changes
    - [x] https://github.com/numba/llvmlite/pull/703 (went to `master`) 
* [x] cherrypick changelog 
     - [x] https://github.com/numba/llvmlite/pull/704 (includes changelog changes)
* [x] annotated tag 0.36.0rc2 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8, 3.9)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud (numba main channel)
* [x] verify wheels for all platforms arrived on PyPi

## numba 0.53.0rc2

* [x] Merge to release branch:
    - [x] https://github.com/numba/numba/pull/6763
* [x] merge change log changes
    - [x] https://github.com/numba/numba/pull/6759
* [x] cherrypick changelog 
     - [x] https://github.com/numba/numba/pull/6759
* [x] annotated tag 0.53.0rc2 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8, 3.9)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud (numba main channel)
* [x] verify wheels for all platforms arrived on PyPi
* [x] Send RC announcement email / post announcement to discourse group
* [x] Post link to twitter

**Comment by esc** [comment]
🎉
