### ISSUE TITLE
Numba 0.53.0rc3 checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#6793]
## llvmlite

nothing(?)

## numba 0.53.0rc2

* [x] merge change log changes
    - [x] https://github.com/numba/numba/pull/6792
* [x] merge for release branch:
    - [x] https://github.com/numba/numba/pull/6791
* [x] cherrypick changelog 
     - [x] https://github.com/numba/numba/pull/6792
* [x] annotated tag 0.53.0rc3 on release branch
* [x] build conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8, 3.9)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud (numba main channel)
* [x] verify wheels for all platforms arrived on PyPi
* [x] Send RC announcement email / post announcement to discourse group
* [x] Post link to twitter

**Comment by esc** [comment]
All tasks have been completed.
