### ISSUE TITLE
0.53.1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#6865]
## numba 0.53.1

* [x] cherry-pick items from the 0.53.1 milestone into a PR
* [x] merge change log modifications and cherry-picks to 0.53 release branch
  * [x] https://github.com/numba/numba/pull/6866
* [x] annotated tag 0.53.1 on release branch
* [x] build and upload conda packages on buildfarm
* [x] build wheels (3.6, 3.7, 3.8, 3.9)
* [x] upload wheels and sdist to PyPI
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`
* [x] verify wheels for all platforms arrived on PyPi
* [x] Send RC announcement email / post announcement to discourse group
* [x] Post link to twitter

### Post release

* [x] cherry-pick change-log modifications to main branch (`master`)

**Comment by esc** [comment]
Discourse: https://numba.discourse.group/t/numba-0-53-1-bugfix-release/637
Twitter: https://twitter.com/numba_jit/status/1375379899893100546
change-log mod PR: https://github.com/numba/numba/pull/6867

All tasks completed, closing issue now. Thank you!
