### ISSUE TITLE
Numba 0.54.0 rc1 llvmlite 0.37.0 RC1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#7164]
## llvmlite

* [x] Merge to `master` (when approved):
    -  None?
* [x] merge change log changes (https://github.com/numba/llvmlite/pull/738)
* [x] Create 0.37 release branch
* [x] Annotated tag v0.37.0rc1 on branch
* [x] build on buildfarm (remember to check the "upload" box)
* [x] move conda packages from `numba/label/dev` to `numba/label/main`
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel

Post RC:
* [x] Tag v0.38.0dev0 on `master` to start new cycle

## Numba 0.54.0  RC1

* [x] Merge to master.
    - [x] "remaining Pull-Requests from milestone".
* [x] Merge change log changes.
    - [x] https://github.com/numba/numba/pull/7154
* [x] Create 0.54 release branch.
* [x] Pin llvmlite to `>=0.37.0rc1,<0.38.0`.
* [x] Annotated tag 0.54.0rc1 on release branch.
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [x] Verify ReadTheDocs build.
* [x] Post announcement to discourse group.
* [x] Post link to Twitter.
* [x] Post link to EveryoneSocial

### Post Release:

* [x] Tag 0.55.0dev0 to start new development cycle on `master`.
* [x] Update llvmlite dependency spec to match next version via PR to `master`.
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Q: not sure it makes sense to post about an RC on python-announce, maybe only for the final, don't want to flood peoples inboxes with noisy RC announcements. Anyone else have an opinion?

**Comment by sklam** [comment]
i also think we should only post once we have the final to  not spam python-announce

**Comment by esc** [comment]
> i also think we should only post once we have the final to not spam python-announce

OK, I have removed that task from the list above.

**Comment by stuartarchibald** [comment]
> > i also think we should only post once we have the final to not spam python-announce
> 
> OK, I have removed that task from the list above.

Does this need also patching out of the issue template?

**Comment by esc** [comment]
> > > i also think we should only post once we have the final to not spam python-announce
> > 
> > 
> > OK, I have removed that task from the list above.
> 
> Does this need also patching out of the issue template?

https://github.com/numba/numba/pull/7197

**Comment by esc** [comment]
To close this checklist I have created two additional PRs:

https://github.com/numba/numba/pull/7219

And:

https://github.com/numba/numba/pull/7220

And the milestone is almost empty (only this issue left):

https://github.com/numba/numba/milestone/52

**Comment by esc** [comment]
All complete, closing issue now.
