### ISSUE TITLE
Numba 0.54.0 rc2 | llvmlite 0.37.0 rc2 | Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#7206]
## llvmlite 0.37.0rc2

* [x] Merge to `master` (when approved):
    - [x] https://github.com/numba/llvmlite/pull/736
    - [x] https://github.com/numba/llvmlite/pull/747
    - [x] https://github.com/numba/llvmlite/pull/748
    - [x] https://github.com/numba/llvmlite/pull/749
* [x] Cherry-Pick from `master` onto `release0.37`branch
    - [x] Merge: https://github.com/numba/llvmlite/pull/745 comprising:
      - (https://github.com/numba/llvmlite/pull/736)
    - [x] Merge: https://github.com/numba/llvmlite/pull/750 comprising:
      - (https://github.com/numba/llvmlite/pull/747)
      - ( https://github.com/numba/llvmlite/pull/748)
      - ( https://github.com/numba/llvmlite/pull/749)
* [x] merge change log changes (https://github.com/numba/llvmlite/pull/XXX)
* [x] Annotated tag v0.37.0rc2 on `release0.37` branch
* [x] build and upload conda packages on buildfarm (remember to check the "upload" box)
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] move conda packages from `numba/label/dev` to `numba/label/main`
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel
* [x] Verify ReadTheDocs build.

## numba 0.54.0rc2

* [x] Merge rc2 PRs
  * [x] https://github.com/numba/numba/pull/7196
* [x] Cherry-pick items from the 0.54.0rc2 milestone into a PR.
  * [x]  https://github.com/numba/numba/pull/7211
* [x] Merge any release only PRs
  * [x] https://github.com/numba/numba/pull/7209
* [x] Merge change log modifications and cherry-picks to 0.54 release branch.
  * [x] https://github.com/numba/numba/pull/XXXX
* [x] Annotated tag 0.54.0rc2 on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
* [x] Clean up `ci_artifacts`.
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
* [x] Post link to Twitter.

### Post release

* [x] Update release checklist template.
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Note for the final: we should probably remember to drop Python 3.6 support from llvmlite.

**Comment by esc** [comment]
> Note for the final: we should probably remember to drop Python 3.6 support from llvmlite.

https://github.com/numba/llvmlite/pull/747

**Comment by esc** [comment]
Picking up from last week, completed builds on the Anaconda internal build farm:

* llvmlite was fine
* nuba was fine
* llvmlite wheel was fine (except 3.6 tasks, which was to be expected given the removal of 3.6)
* numba wheel was fine 

I'll transition the build artifacts to the appropriate channels for dissemination now.

**Comment by esc** [comment]
RTD build for llvmlite had to be activated manually: https://llvmlite.readthedocs.io/en/v0.37.0rc2/

**Comment by esc** [comment]
RTD build for numba also: https://numba.readthedocs.io/en/0.54.0rc2/

**Comment by esc** [comment]
https://numba.discourse.group/t/numba-0-54-0-rc2-and-llvmlite-v0-37-0-rc2/810

**Comment by esc** [comment]
> * [ ]  Cherry-pick change-log modifications to main branch (`master`) via PR.

Since we adopted the new policy of committing changes directly to master and cherry-picking them into the release branch, I don't think this bullet is needed anymore?

**Comment by esc** [comment]
> > * [ ]   Cherry-pick change-log modifications to main branch (`master`) via PR.
> 
> Since we adopted the new policy of committing changes directly to master and cherry-picking them into the release branch, I don't think this bullet is needed anymore?

I've added that change to:

https://github.com/numba/numba/pull/7220

**Comment by esc** [comment]
all done here, closing now
