### ISSUE TITLE
Numba 0.54.0rc3 Checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#7274]
## numba 0.54.0rc3

* [x] Cherry-pick items from the 0.54.0rc3 milestone into a PR.
* [x] Merge change log modifications and cherry-picks to 0.54 release branch.
  * [x] https://github.com/numba/numba/pull/7275
* [x] Annotated tag 0.54.0rc3 on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload"). `numba_yaml_79`
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm. `numba_wheel_50`
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
* [x] Clean up `ci_artifacts`.
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
* [x] Post link to Twitter.

### Post release

* [x] Close milestone (and then close this release issue).
