### ISSUE TITLE
Numba 0.54.0 Final Checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#7323]
## llvmlite

* [x] Merge to `master` (when approved):
    -  None?
* [x] merge change log changes (https://github.com/numba/llvmlite/pull/764)
* [x] cherry picks https://github.com/numba/llvmlite/pull/766
* [x] Annotated tag v0.37.0 on branch
* [x] build on buildfarm (remember to check the "upload" box)
* [x] build wheels (3.6, 3.7, 3.8, 3.9) (remember to check the "upload" box)
* [x] move conda packages from `numba/label/dev` to `numba/label/main`
* [x] upload wheels and sdist to PyPI
* [x] verify conda packages uploaded to Anaconda Cloud and in main channel
* [x] verify wheels for all platforms arrived on PyPi

## numba 0.54.0

* [x] Cherry-pick items from the 0.54.0 milestone into a PR.
* [x] Merge change log modifications and cherry-picks to 0.54 release branch.
  * [x] changelog https://github.com/numba/numba/pull/7319
  * [x] cherrypicks https://github.com/numba/numba/pull/7320
* [ ] Review, merge and check execution of release notebook. (FINAL ONLY)
* [x] Annotated tag 0.54.0 on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
* [x] Clean up `ci_artifacts`.
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
* [x] Post link to Twitter.
* ~[ ] Post link to python-announce-list@python.org.~

### Post release

* [x] Update release checklist template.
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Close milestone (and then close this release issue).
