### ISSUE TITLE
Numba 0.54.1rc1 Checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#7431]
## numba 0.54.1rc1

* [x] Cherry-pick items from the X.Y.Z milestone into a PR.
* [x] Merge change log modifications and cherry-picks to X.Y release branch.
    * [x] https://github.com/numba/numba/pull/7430
* [x] Annotated tag 0.54.1rc1 on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`. https://anaconda.org/numba/numba/files?version=0.54.1rc1
* [x] Verify wheels for all platforms arrived on PyPi. https://pypi.org/project/numba/0.54.1rc1/
* [x] Verify ReadTheDocs build. https://numba.readthedocs.io/en/0.54.1rc1/
* [x] Clean up `ci_artifacts`.
* [x] Send RC/FINAL announcement email / post announcement to discourse group. https://numba.discourse.group/t/numba-0-54-1-bugfix-release-rc1/937
* [x] Post link to Twitter.

### Post release

* [x] Update release checklist template.
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Checklist update is here https://github.com/numba/numba/pull/7432

**Comment by esc** [comment]
@sklam is this for `0.54.1` or `0.54.1rc1`
