### ISSUE TITLE
Numba 0.54.1 Checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#7464]
## numba 0.54.1

* [x] Cherry-pick items from the 0.54.1 milestone into a PR.
    * None
* [x] Merge change log modifications and cherry-picks to 0.54 release branch.
  * [x] https://github.com/numba/numba/pull/7465
* [ ] Review, merge and check execution of release notebook. (FINAL ONLY)
* [x] Annotated tag 0.54.1 on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload"). `numba_yaml_100`
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm. `numba_wheel_53`
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
* [x] Clean up `ci_artifacts`.
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
* [x] Post link to Twitter.
~* [ ] Post link to python-announce-list@python.org.~

### Post release

* [x] Update release checklist template.
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
* [x] Close milestone (and then close this release issue).
