### ISSUE TITLE
Numba 0.55.0rc1 Checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#7657]
## Numba 0.55.0rc1

* [x] Merge to master.
    - [x] https://github.com/numba/numba/pull/7082
* [x] Merge change log changes.
    - [x] https://github.com/numba/numba/issues/7644
* [x] Create 0.55 release branch. https://github.com/numba/numba/tree/release0.55
* [x] Pin llvmlite to `>=0.38.0rc1,<0.39`.
* [x] Pin tbb https://github.com/numba/numba/issues/7620
* [x] Pin Numpy to `<=1.21`
* [x] Annotated tag 0.55.0rc1 on release branch.
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm (check "upload").
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Upload PyPi source distribution (`sdist`)
* [x] Initialize and verify ReadTheDocs build.
* [x] Clean up `ci_artifacts`.
* [x] Send RC announcement email / post announcement to discourse group. https://numba.discourse.group/t/numba-0-55-0-rc1/1075
* [x] Post link to Twitter. https://twitter.com/numba_jit/status/1471785352159326209

### Post Release:

* [x] Tag 0.56dev0 to start new development cycle on `master`.
* [x] Update llvmlite dependency spec to match next version via PR to `master` (https://github.com/numba/numba/pull/7718).
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release. (https://github.com/numba/numba/pull/7732)
* [x] Close milestone (and then close this release issue).

**Comment by stonebig** [comment]
It seems no wheel landed (or remained) on [pypi](https://pypi.org/project/numba/0.55.0rc1/#files) for numba-0.55.0rc1-cp310-cp310-win_amd64.whl.
Is it normal ?

**Comment by esc** [comment]
> It seems no wheel landed (or remained) on [pypi](https://pypi.org/project/numba/0.55.0rc1/#files) for numba-0.55.0rc1-cp310-cp310-win_amd64.whl. Is it normal ?

This is correct, we were unable to build the wheels for that platform in December 2021. Hopefully this will be remedied in the upcoming release candidate 2.

**Comment by mthrok** [comment]
Hi - Do you have the timeline for the release? I am updating NumPy >= 1.21, following https://github.com/advisories/GHSA-6p56-wp2h-9hxr and  currently restricted by Numba restriction.

**Comment by esc** [comment]
> Hi - Do you have the timeline for the release? I am updating NumPy >= 1.21, following [GHSA-6p56-wp2h-9hxr](https://github.com/advisories/GHSA-6p56-wp2h-9hxr) and currently restricted by Numba restriction.

Thank you for asking about this. There is no concrete timeline, but since we are in the middle of a release candidate phase the final should become available in a couple -- maybe two to five -- of weeks or something like that.

**Comment by esc** [comment]
> > Hi - Do you have the timeline for the release? I am updating NumPy >= 1.21, following [GHSA-6p56-wp2h-9hxr](https://github.com/advisories/GHSA-6p56-wp2h-9hxr) and currently restricted by Numba restriction.
> 
> Thank you for asking about this. There is no concrete timeline, but since we are in the middle of a release candidate phase the final should become available in a couple -- maybe two to five -- of weeks or something like that.

Feel free to look at https://github.com/numba/numba/milestone/62 as a rough indicator of progress.

**Comment by esc** [comment]
@sklam FYI: llvmlite `v0.39.0dev0` was tagged this morning and build artifacts are available in `numba/label/dev` on anaconda.org: https://anaconda.org/numba/llvmlite/files?version=0.39.0dev0

**Comment by esc** [comment]
> @sklam FYI: llvmlite `v0.39.0dev0` was tagged this morning and build artifacts are available in `numba/label/dev` on anaconda.org: https://anaconda.org/numba/llvmlite/files?version=0.39.0dev0

This means, we can proceed with: `Update llvmlite dependency spec to match next version via PR to master.`

**Comment by esc** [comment]
release checklist update is now here: https://github.com/numba/numba/pull/7732

**Comment by esc** [comment]
With 0.55.0 out now, https://numba.discourse.group/t/numba-0-55-0-and-llvmlite-0-38-0-final-release/1136 closing this!
