### ISSUE TITLE
Numba 0.55.0 FINAL Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#7735]
## numba 0.55.0 FINAL

* [x] Merge changelog changes to `master`(https://github.com/numba/numba/pull/7736)
* [x] Cherry pick change log modifications onto release branch. (d44b8f446e7df00d43994a39e9109f22f376f7a7)
* [x] Annotated tag 0.55.0 on release branch (no `v` prefix) (https://github.com/numba/numba/tree/0.55.0).
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
* [x] Clean up `ci_artifacts`.
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
* [x] Post link to Twitter.
* [x] Post link to python-announce-list@python.org. (https://mail.python.org/archives/list/python-announce-list@python.org/thread/XJKKIWASMOXQMNAEF2KLBYM2OAAYQVFS/)

### Post release

* [x] Update release checklist template. (no changes)
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
* [x] Close milestone (and then close this release issue). (no milestone)

**Comment by esc** [comment]
## Delayed

* [ ] Review, merge and check execution of release notebook. (FINAL ONLY)

**Comment by esc** [comment]
It is done.

**Comment by esc** [comment]
Demo notebook(s) will be released for 0.55.1
