### ISSUE TITLE
Numba 0.55.1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#7781]
## numba 0.55.1

* [x] Cherry-pick items from the 0.55.1 milestone into a PR. https://github.com/numba/numba/pull/7789
* [x] Approve change log modifications and cherry-pick. https://github.com/numba/numba/pull/7796  
* [x] Merge cherry-picks to 0.55 release branch.
  * [x] https://github.com/numba/numba/pull/7789
* [x] Review, merge and check execution of release notebook. (FINAL ONLY)
* [x] Annotated tag 0.55.1 on release branch (no `v` prefix). https://github.com/numba/numba/releases/tag/0.55.1
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`). https://pypi.org/project/numba/0.55.1/#files
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build. https://numba.readthedocs.io/en/0.55.1/
* [x] Send RC/FINAL announcement email / post announcement to discourse group. https://numba.discourse.group/t/ann-numba-0-55-1/1161
* [x] Post link to Twitter. https://twitter.com/numba_jit/status/1486837224675192834
* [x] Post link to python-announce-list@python.org. https://mail.python.org/archives/list/python-announce-list@python.org/thread/XK5OLCC6TDYFICKYWJRDVJELQC6YXEJS/

### Post release

* [x] Clean up `ci_artifacts`.
* [x] Update release checklist template. https://github.com/numba/numba/pull/7799
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY). https://github.com/numba/numba/releases/tag/0.55.1
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Looks like we may need to merge the reminaing PRs in https://github.com/numba/numba/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Numba+0.55.1%22 first.

**Comment by esc** [comment]
Cherry-pick PR is open: #7789 -- waiting for remaining PRs from the milestone.

**Comment by esc** [comment]
Running build farm `Build numba_yaml_150 has started` on the cherry-pick PR at #7789

**Comment by esc** [comment]
unable to run cherry-pick PR on the build farm due to conflicts with master

**Comment by esc** [comment]
Now running on the SHA pointed to by the `refs/pull/7789` reference: cdcd7b9

**Comment by esc** [comment]
> Now running on the SHA pointed to by the `refs/pull/7789` reference: [cdcd7b9](https://github.com/numba/numba/commit/cdcd7b90c2502dd1a49a508dbaca170b4da35682)

Unfortunately this did not work either, b/c our build farm is not configured (yet) to fetch all SHA's for pull-requests too.

**Comment by esc** [comment]
> > Now running on the SHA pointed to by the `refs/pull/7789` reference: [cdcd7b9](https://github.com/numba/numba/commit/cdcd7b90c2502dd1a49a508dbaca170b4da35682)
> 
> Unfortunately this did not work either, b/c our build farm is not configured (yet) to fetch all SHA's for pull-requests too.

I reconfigured it temporarily and the build is now running.

**Comment by esc** [comment]
The number of cherry-picked commits on this branch corresponds to the total closed PRs in the 0.55.1 milestone: 14

```
$ git log --oneline --no-decorate release0.55..cherry_pick_for_0.55.1 | wc -l
14 
```

And here is a plain-text list of PR Numbers:

```
$ git log --oneline --no-decorate release0.55..cherry_pick_for_0.55.1 | cut -d' ' -f5
#7755
#7749
#7744
#7712
#7729
#7788
#7752
#7748
#7745
#7740
#7724
#7709
#7704
#7619
```

**Comment by esc** [comment]
Change-log PR is now live: https://github.com/numba/numba/pull/7796 -- would suggest to review this and then cherry-pick the commit itself (or the squashed version of it?) to the cherry-pick PR.

**Comment by esc** [comment]
#7796 was merged and cherry-picked

**Comment by esc** [comment]
tag is live: https://github.com/numba/numba/releases/tag/0.55.1

**Comment by esc** [comment]
Builds in progress...

**Comment by esc** [comment]
Wheels are live: https://pypi.org/project/numba/0.55.1/#files

**Comment by esc** [comment]
conda packages have arrived:

```
 💣 zsh» for i in linux-64 linux-32 linux-ppc64le linux-aarch64 win-64 win-32 osx-64; do; CONDA_SUBDIR="$i" echo "Subdir: $i" && CONDA_SUBDIR="$i" conda search -c numba/label/main numba==0.55.1 ; done ;
Subdir: linux-64
Loading channels: done
# Name                       Version           Build  Channel
numba                         0.55.1 np1.11py3.7hc13618b_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.11py3.8hc13618b_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.16py3.9h59fbc97_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.21py3.10ha54aa7d_g76720bf88_0  numba/label/main
Subdir: linux-32
Loading channels: done
# Name                       Version           Build  Channel
numba                         0.55.1 np1.11py3.7h04863e7_g76720bf88_0  numba/label/main
Subdir: linux-ppc64le
Loading channels: done
# Name                       Version           Build  Channel
numba                         0.55.1 np1.11py3.7hc13618b_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.11py3.8hc13618b_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.19py3.9hab34e9b_g76720bf88_0  numba/label/main
Subdir: linux-aarch64
Loading channels: done
# Name                       Version           Build  Channel
numba                         0.55.1 np1.11py3.7h77ed09d_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.16py3.8h8925633_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.19py3.9he8f520d_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.21py3.10hfbc5805_g76720bf88_0  numba/label/main
Subdir: win-64
Loading channels: done
# Name                       Version           Build  Channel
numba                         0.55.1 np1.11py3.7hf9181ef_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.11py3.8h7b37a8b_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.16py3.9h5685391_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.21py3.10hd3205ba_g76720bf88_0  numba/label/main
Subdir: win-32
Loading channels: done
# Name                       Version           Build  Channel
numba                         0.55.1 np1.11py3.7h9d3e9c7_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.16py3.9h856c743_g76720bf88_0  numba/label/main
numba                         0.55.1 np1.21py3.10h41d8588_g76720bf88_0  numba/label/main
Subdir: osx-64
Loading channels: done
# Name                       Version           Build  Channel
numba                         0.55.1 np1.11py3.7hbb42477_g76720bf_0  numba/label/main
numba                         0.55.1 np1.11py3.8hbb42477_g76720bf_0  numba/label/main
numba                         0.55.1 np1.16py3.9h2fabc88_g76720bf_0  numba/label/main
numba                         0.55.1 np1.21py3.10hf701924_g76720bf_0  numba/label/main
```

**Comment by esc** [comment]
Announced: https://numba.discourse.group/t/ann-numba-0-55-1/1161

**Comment by esc** [comment]
OK folks, that's all for now, remaining items to be completed soon.

**Comment by esc** [comment]
I posted to python-announce-list@python.org

**Comment by esc** [comment]
Checklist update is here: https://github.com/numba/numba/pull/7799

**Comment by esc** [comment]
GitHub release is live: https://github.com/numba/numba/releases/tag/0.55.1

**Comment by stuartarchibald** [comment]
Think this is waiting on https://github.com/numba/numba-examples/pull/41
