### ISSUE TITLE
Numba 0.55.2 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#8066]
## numba 0.55.2

* [x] Backport NumPy 1.22 patch 
  * https://github.com/numba/numba/pull/8067
  * Bump the maximum supported NumPy version in `setup.py` and `numba/__init__.py`:  
  * https://github.com/numba/numba/pull/8075
  * https://github.com/numba/numba/pull/8103
* [x] Backports for M1:
  * https://github.com/numba/numba/pull/8093
  * https://github.com/numba/numba/pull/8098
* [x] Other Backports:
  * https://github.com/numba/numba/pull/8082
  * https://github.com/numba/numba/pull/8078
  * https://github.com/numba/numba/pull/8094
  * https://github.com/numba/numba/pull/8100
  * https://github.com/numba/numba/pull/8114
* [x] Create PR for changelog modifications to target release branch
  * https://github.com/numba/numba/pull/8068 
* [x] Create PRs to fix public CI build failures on the release branch
  *  https://github.com/numba/numba/pull/8069
  * https://github.com/numba/numba/pull/8084
* [x] Merge change log modifications and backports to 0.55 release branch.
* [x] Annotated tag 0.55.2 on release branch (no `v` prefix).
  * https://github.com/numba/numba/releases/tag/0.55.2 
* [x] Build and upload conda packages on buildfarm (check `upload`).
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
  * https://anaconda.org/numba/numba/files?version=0.55.2
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
  * https://pypi.org/project/numba/0.55.2/#files 
* [x] Verify ReadTheDocs build.
  * https://numba.readthedocs.io/en/0.55.2/
  * https://numba.readthedocs.io/en/0.55.2
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
  * https://numba.discourse.group/t/ann-numba-0-55-2/1353 
* [x] Post link to Twitter.
  * https://twitter.com/numba_jit/status/1529743486374887425 
* [x] Post link to python-announce-list@python.org.

### Post release

* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template.
  * https://github.com/numba/numba/pull/8118
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
  * https://github.com/numba/numba/releases/tag/0.55.2 
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Notes for this release:

a) There will be no demo notebook
b) The `sdist` is now built as part of the CI system and no longer needs to be built locally.

**Comment by esc** [comment]
The 1.22 backport generated the following conflict on cherry-pick:

```
diff --cc docs/source/user/installing.rst
index de71c57c2e,94a14ea060..0000000000
--- i/docs/source/user/installing.rst
+++ w/docs/source/user/installing.rst
@@@ -260,6 -261,46 +260,49 @@@ vary with target operating system and h
    * ``numpydoc``
    * ``make`` as an executable on the ``$PATH``

++<<<<<<< HEAD
++=======
+ .. _numba_support_info:
+
+ Version support information
+ ---------------------------
+
+ This is the canonical reference for information concerning which versions of
+ Numba's dependencies were tested and known to work against a given version of
+ Numba. Other versions of the dependencies (especially NumPy) may work reasonably
+ well but were not tested. The use of ``x`` in a version number indicates all
+ patch levels supported. The use of ``?`` as a version is due to missing
+ information.
+
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+ | Numba  | Release date | Python                    | NumPy                      | llvmlite                     | LLVM              | TBB                         |
+ +========+==============+===========================+============================+==============================+===================+=============================+
+ | 0.56.x | TBC          | 3.7.x <= version < 3.11   | 1.18 <= version < 1.23     | 0.39.x                       | 11.x              | 2021.x                      |
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+ | 0.55.x | 2022-01-13   | 3.7.x <= version < 3.11   | 1.18 <= version < 1.22     | 0.38.x                       | 11.x              | 2021.x                      |
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+ | 0.54.x | 2021-08-19   | 3.6.x <= version < 3.10   | 1.17 <= version < 1.21     | 0.37.x                       | 11.x              | 2021.x                      |
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+ | 0.53.x | 2021-03-11   | 3.6.x <= version < 3.10   | 1.15 <= version < 1.21     | 0.36.x                       | 11.x              | 2019.5 <= version < 2021.4  |
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+ | 0.52.x | 2020-11-30   | 3.6.x <= version < 3.9    | 1.15 <= version < 1.20     | 0.35.x                       | 10.x              | 2019.5 <= version < 2020.3  |
+ |        |              |                           |                            |                              | (9.x for aarch64) |                             |
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+ | 0.51.x | 2020-08-12   | 3.6.x <= version < 3.9    | 1.15 <= version < 1.19     | 0.34.x                       | 10.x              | 2019.5 <= version < 2020.0  |
+ |        |              |                           |                            |                              | (9.x for aarch64) |                             |
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+ | 0.50.x | 2020-06-10   | 3.6.x <= version < 3.9    | 1.15 <= version < 1.19     | 0.33.x                       | 9.x               | 2019.5 <= version < 2020.0  |
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+ | 0.49.x | 2020-04-16   | 3.6.x <= version < 3.9    | 1.15 <= version < 1.18     | 0.31.x <= version < 0.33.x   | 9.x               | 2019.5 <= version < 2020.0  |
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+ | 0.48.x | 2020-01-27   | 3.6.x <= version < 3.9    | 1.15 <= version < 1.18     | 0.31.x                       | 8.x               | 2018.0.5 <= version < ?     |
+ |        |              |                           |                            |                              | (7.x for ppc64le) |                             |
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+ | 0.47.x | 2020-01-02   | 3.5.x <= version < 3.9;   | 1.15 <= version < 1.18     | 0.30.x                       | 8.x               | 2018.0.5 <= version < ?     |
+ |        |              | version == 2.7.x          |                            |                              | (7.x for ppc64le) |                             |
+ +--------+--------------+---------------------------+----------------------------+------------------------------+-------------------+-----------------------------+
+
++>>>>>>> 468647dddd... Merge pull request #8027 from stuartarchibald/wip/np122
  Checking your installation
  --------------------------
```
AFAICT the version support table was not part of 0.55 -- so I elected to remove the version support table completely from the patch release.

**Comment by esc** [comment]
Additional CI configuration was required: https://github.com/numba/numba/pull/8069

**Comment by esc** [comment]
#8067 and #8069 were deadlocked so https://github.com/numba/numba/pull/8070 was created.

**Comment by esc** [comment]
> #8067 and #8069 were deadlocked so #8070 was created.

#8070 was broken and had to be abandoned, so was #8071 and we are now looking at #8072

Also, #8073 had to be created since the release branch didn't have the `master` -> `main` changes. This has now also been included in #8072 for testing.

**Comment by esc** [comment]
There are now 4 PRs pertaining to this task:

#8075
#8073
#8069
#8068

Since all of these depend on each other in one way or another, there is also #8072 which combines all of the above.

**Comment by esc** [comment]
#8073 will need a re-roll to be a backport of #7804 https://github.com/numba/numba/pull/8073#issuecomment-1131819978

**Comment by esc** [comment]
#8073 was replaced by https://github.com/numba/numba/pull/8078

**Comment by esc** [comment]
https://github.com/numba/numba/pull/8072 has been re-rolled and now contains:

#8075 #8078 #8069 #8068 #8067

**Comment by esc** [comment]
> #8072 has been re-rolled and now contains:
> 
> #8075 #8078 #8069 #8068 #8067

was all 🟢 again

**Comment by sklam** [comment]
Two more PRs are needed: https://github.com/numba/numba/pull/8082,  https://github.com/numba/numba/pull/8084
combined for testing at: https://github.com/numba/numba/pull/8083

**Comment by esc** [comment]
An additional backport was needed: https://github.com/numba/numba/pull/8093

I have merged and pushed that onto the #8083 PR and added it to the list of required backports in the checklist above.

**Comment by esc** [comment]
An additional backport was needed: https://github.com/numba/numba/pull/8094

I have merged and pushed that onto the https://github.com/numba/numba/pull/8083 PR and added it to the list of required backports in the checklist above.

**Comment by esc** [comment]
During the release process the following issue was detected: https://github.com/numba/numba/pull/8097 -- a backport is available here:  https://github.com/numba/numba/pull/8098

I have merged and pushed that onto the https://github.com/numba/numba/pull/8083 PR and added it to the list of required backports in the checklist above.

**Comment by esc** [comment]
> Note to selves: #7786 was never backported and only exists as a cherry-pick on #8083 -- it must be backported before the release.

It is now here: https://github.com/numba/numba/pull/8100

**Comment by skapin** [comment]
Do you have a date for the release of 0.55.2 ?

**Comment by esc** [comment]
> Do you have a date for the release of 0.55.2 ?

No, there is no date as we can not forsee exactly when it will be ready. There are 4 PRs remaining in the 0.55.2 milestone and there is an integration PR testing these final patches here: https://github.com/numba/numba/pull/8083 -- we hope that no further issues will arise and that packages should become available in the next few days.

**Comment by esc** [comment]
I have updated the changelog PR to include all discovered backports: https://github.com/numba/numba/pull/8068

**Comment by esc** [comment]
The combine PR #8083 passed all Anaconda internal tests.

**Comment by esc** [comment]
All remaining PRs have been merged.

**Comment by esc** [comment]
Release has been tagged: https://github.com/numba/numba/releases/tag/0.55.2

**Comment by esc** [comment]
The RTD build as completed and the docs are live.

**Comment by esc** [comment]
I have scheduled all the builds for the conda packages and wheels -- it will now take about 12 -18 hours to produce the build artifacts and packages and wheels will be uploaded once this process has completed successfully.

**Comment by esc** [comment]
Packages have been uploaded.

**Comment by esc** [comment]
Announcements have been posted!

**Comment by skapin** [comment]
the news 0.55.2 is published on conda -c numba, but not on conda-forge or default anaconda channel. It's still the 0.55.1 as latest.
Can we safely use the 0.55.2 from -c numba ? When is the release on default ? What is the worflow for it to be delivered ?

Thank you for your awsome work ! :+1:

**Comment by gmarkall** [comment]
> Can we safely use the 0.55.2 from -c numba ?

Probably - safely could mean several things, but some possible answers are:

- The version on the channel is not a prerelease, it should practically be the same as the version that will be on conda-forge or the default channels.
- The numba channel is managed by the Numba developers, and therefore the packages there are as trustworthy as the Numba developers and all involved infrastrcture for getting the packages there.
- Using this package is no more likely to get conda dependency resolution in a mess than using a package from the conda-forge or default channels.

If you meant something other than the above by "safely", could you please clarify what you mean?

> What is the worflow for it to be delivered ?

- For conda-forge, this PR is adding 0.55.2: https://github.com/conda-forge/numba-feedstock/pull/93.
- For defaults, it will be dependent upon Anaconda adding it to the channel.

**Comment by skapin** [comment]
Thank you, your answer is perfect :) :+1:

**Comment by esc** [comment]
All items completed.
