### ISSUE TITLE
*args Issue Tracking Megathread

### ISSUE THREAD

**Issue by njriasan** [numba/numba#8108]
## Issue Tracking

As discussed in the May 10th Numba developer meeting, this is an issue meant to track the various *args issues that have been reported inside Numba. I determined these by searching `*args` and `star` in the issues, so there may be some I have missed.

### njit

- [ ] #8059: Segfault with objmode
- [ ] #6894: Support *args in closures
- [ ] #2770: Unpack list to *args not supported
- [ ] #5304: Tuple unpacking + keyword arguments not supported

### overload

- [ ] #7933: Check if *args is empty inside an overload
- [ ] #5291: Tuple unpacking + keyword arguments not supported in overloads

### cuda

- [ ] #6891: `*args` treated as a normal argument in CUDA

### vectorize

- [ ] #6954: Support for *args

### type_callable

- [ ] #7973: Support for *args

**Comment by gmarkall** [comment]
I'm not sure this needs triage or going stale, so I'm going to remove both.

**Comment by gmarkall** [comment]
I've added "discussion" as this seems most appropriate (and I don't want to leave this unlabelled because then it looks like the label was forgotten).

**Comment by sklam** [comment]
https://github.com/numba/numba/issues/9791 is likely another case
