### ISSUE TITLE
Numba 0.56.0rc1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#8204]
## Numba 0.56.0rc1

* [x] Merge to main.
    - [x] "remaining Pull-Requests from milestone".
* [x] Check Numba's version support table documentation. Update via PR if
      needed.
  . https://github.com/numba/numba/pull/8189
* [x] Review deprecation schedule and notices. Make PRs if need be.
  - https://github.com/numba/numba/issues/7770
* [x] Merge change log changes.
    - [x] "[PR with changelog entries](https://github.com/numba/numba/pull/8192)".
* [x] Create 0.56 release branch.
  - https://github.com/numba/numba/tree/release0.56
* [x] Dependency version pinning on release branch
  * [x] Pin llvmlite to `>=0.39.0rc1,<0.40.0`.
  * [x] Pin NumPy if needed (1.22?)
  * [x] Pin TBB if needed (probably not, already pinned on `main`)
  * https://github.com/numba/numba/pull/8205
* [x] Annotated tag 0.56.0rc1 on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload"). (BFID `numba_yaml_212`)
* [x] Build wheels and sdist on the buildfarm (check "upload"). (BFID `numba_wheel_67`)
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
  - https://anaconda.org/numba/numba/files?version=0.56.0rc1
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
  - https://pypi.org/project/numba/0.56.0rc1/#files
* [x] Initialize and verify ReadTheDocs build.
  - https://numba.readthedocs.io/en/0.56.0rc1/
* [x] Send RC announcement email / post announcement to discourse group.
  - https://numba.discourse.group/t/ann-numba-0-56-0-rc1/1417
* [x] Post link to Twitter.
  - https://twitter.com/numba_jit/status/1542078519550820352

### Post Release:

* [x] Clean up `ci_artifacts` by moving files to sub-directories
* [x] Tag `0.57.0dev0` to start new development cycle on `main`.
  - https://github.com/numba/numba/releases/tag/0.57.0dev0
* [x] Update llvmlite dependency spec to match next version via PR to `main`.
  - https://github.com/numba/numba/pull/8201
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
  - https://github.com/numba/numba/pull/8198
  - https://github.com/numba/numba/pull/8207
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
It's a wrap!
