### ISSUE TITLE
meta-issue: migrate `@glue_*` functions to `@overload`

### ISSUE THREAD

**Issue by guilhermeleobas** [numba/numba#8254]
Following some recent discussion, this is a meta-issue to track the migration from the `@glue_typing/glue_lowering` API to use `@overload`.

### `numba/core/typing/npydecl.py`
- [x] np.array - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.full - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.full_like - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.identity - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.frombuffer - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.sort - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.asfortranarray - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.ascontiguousarray - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.copy - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.expand_dims - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.concatenate - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.stack - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.hstack - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.vstack - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.dstack - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.column_stack - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.round - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.around - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.sinc - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.angle - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.diag - [PR 8234](https://github.com/numba/numba/pull/8234)
- [x] np.linspace - [PR 8431](https://github.com/numba/numba/pull/8431)
- [x] np.atleast_1d - [PR 8435](https://github.com/numba/numba/pull/8435)
- [x] np.atleast_2d - [PR 8435](https://github.com/numba/numba/pull/8435)
- [x] np.atleast_3d - [PR 8435](https://github.com/numba/numba/pull/8435)
- [x] np.dot - [PR 8256](https://github.com/numba/numba/pull/8256)
- [x] np.vdot - [PR 8256](https://github.com/numba/numba/pull/8256)
- [ ] np.where - [PR 8258](https://github.com/numba/numba/pull/8258)
- [x] np.take - [PR 8431](https://github.com/numba/numba/pull/8431)
- [x] carray- [PR 8432](https://github.com/numba/numba/pull/8432)
- [x] farray - [PR 8432](https://github.com/numba/numba/pull/8432)

### `numba/core/typing/randomdecl.py`

- [x] `np.random.geometric` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.logseries` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.zipf` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.binomial` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.negative_binomial,` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.exponential` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.rayleigh` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.hypergeometric` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.laplace` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.logistic` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.lognormal` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.gamma` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.beta` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.f` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.gumbel` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.vonmises` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.wald` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `random.betavariate` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `random.gammavariate` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `random.lognormvariate` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `random.vonmisesvariate` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `random.weibullvariate` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.chisquare` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.pareto` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.power` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.standard_gamma` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.standard_t` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.weibull` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `random.expovariate` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `random.paretovariate` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.standard_cauchy` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `np.random.standard_exponential` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `random.triangular` - [PR 8061](https://github.com/numba/numba/pull/8061)
- [x] `random.getrandbits` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `random.random` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.random` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.random_sample` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.sample` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.ranf` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `random.randint` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.randint` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `random.randrange` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `random.seed` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.seed` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.poisson` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.normal` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.triangular` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.uniform` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `random.gauss` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `random.normalvariate` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `random.uniform` - [PR 8368](https://github.com/numba/numba/pull/8368)
- [x] `np.random.standard_normal` - [PR 8368](https://github.com/numba/numba/pull/8368)

### `numba/np/linalg.py`

Migrate `@glue_lowering` to `@overload`

- [x] `np.dot` - [PR 8256](https://github.com/numba/numba/pull/8256)
- [x] `np.vdot` - [PR 8256](https://github.com/numba/numba/pull/8256)

### `numba/np/arraymath.py`

- [ ] np.sum - [PR 8420](https://github.com/numba/numba/pull/8420)
- [ ] np.nonzero
- [x] np.prod - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] np.cumsum - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] np.cumprod - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] np.mean - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] np.var - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] np.std - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] np.min - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] np.max - [PR 8415](https://github.com/numba/numba/pull/8415)
- [ ] array.sum
- [ ] array.nonzero
- [x] array.prod - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] array.cumsum - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] array.cumprod - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] array.mean - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] array.var - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] array.std - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] array.min - [PR 8415](https://github.com/numba/numba/pull/8415)
- [x] array.max - [PR 8415](https://github.com/numba/numba/pull/8415)

**Comment by apmasell** [comment]
I'm working on the linalg and other random `@glue_lowering`

**Comment by apmasell** [comment]
The remaining random functions are in #8368 and the linear algebra ones are in #8256

**Comment by apmasell** [comment]
Final cleanup in #8649

**Comment by stuartarchibald** [comment]
Many thanks to everyone who contributed to this migration of functionality across APIs!
