### ISSUE TITLE
Numba 0.56.0 Checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#8260]
## numba 0.56.0

* [x] merge https://github.com/numba/numba/pull/8255
* [x] Cherry-pick items from the 0.56.0 milestone into a PR.
    * [x] https://github.com/numba/numba/pull/8269
* [x] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY).
  * [x] Make, approve and merge PR against the 0.56 release branch. (#8274, but it's against `main`).
  * [x] Create a cherry-pick PR of the above against release branch. (https://github.com/numba/numba/pull/8279)
* [x] Approve change log modifications and cherry-pick (#8275).
* [x] Merge change log modifications and cherry-picks to X.Y release branch.
  * [x] https://github.com/numba/numba/pull/8279
* ~~[ ] Review, merge and check execution of release notebook. (FINAL ONLY)~~
* [x] Annotated tag 0.56.0 on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check `upload`).
* [x] Build wheels and sdist on the buildfarm (check "upload").
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
  * https://anaconda.org/numba/numba/files?version=0.56.0
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
  * https://pypi.org/project/numba/#files
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
  * https://numba.readthedocs.io/en/0.56.0/ 
* [x] Post link to Twitter.
  * https://twitter.com/numba_jit/status/1551878781102690304
* [x] Post announcement to discourse group
  * https://numba.discourse.group/t/ann-numba-0-56-0/1461
* [x] Post link to python-announce-list@python.org.
  * https://mail.python.org/archives/list/python-announce-list@python.org/thread/RMTHNAIUEJ7YX57QOQXGO4U4BVEJRLDH/ 

### Post release

* [x] Snapshot Build Farm config
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
  * https://github.com/numba/numba/pull/8292
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
  * https://github.com/numba/numba/releases/tag/0.56.0 
* [x] Close milestone (and then close this release issue).
