### ISSUE TITLE
Numba ~~0.56.1~~ 0.56.2 Checklist

### ISSUE THREAD

**Issue by apmasell** [numba/numba#8406]
## numba ~~0.56.1~~ 0.56.2

* [X] Cherry-pick items from the 0.56.1 milestone into a PR. (https://github.com/numba/numba/pull/8392)
* [X] Pin NumPy version https://github.com/numba/numba/pull/8392
* [x] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY).
  * [x] Make, approve and merge a PR against the `main` branch. (https://github.com/numba/numba/pull/8411)
  * [x] Create a cherry-pick from the merge and include in the cherry-pick-PR
    for the `release0.56.1` branch.
* [x] Approve change log modifications and cherry-pick.
* [x] Merge change log modifications and cherry-picks to 0.56.1 release branch.
  * [x] https://github.com/numba/numba/pull/8392
* switch to 0.56.2 due to mistake in 0.56.1
* [x] Annotated tag 0.56.2 on release branch (no `v` prefix). (https://github.com/numba/numba/tree/0.56.2)
* [x] Build and upload conda packages on buildfarm (check `upload`). `numba_yaml_244`
* [x] Build wheels and sdist on the buildfarm (check "upload"). `numba_wheel_73`
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`. (https://anaconda.org/numba/numba/files?version=0.56.2)
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi. (https://pypi.org/project/numba/#files)
* [x] Verify ReadTheDocs build. (https://numba.readthedocs.io/en/0.56.2/)
* [x] Post announcement to discourse group 
 * https://numba.discourse.group/t/ann-numba-0-56-2-llvmlite-0-39-1/1542
* [x] Post link to Twitter. (https://twitter.com/numba_jit/status/1565702324294746115)
* [x] Post link to python-announce-list@python.org.

### Post release

* [x] Snapshot Build Farm config
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release. (https://github.com/numba/numba/pull/8421)
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY). (https://github.com/numba/numba/releases/tag/0.56.2)
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Note to self: need to add "check NumPy pin and modify if need be" to the release checklist post release.

**Comment by esc** [comment]
Unfortunately, we encountered a build issue after tagging. The 0.56.1 was scrapped, there is only a tag on github. We will proceed immediately to 0.56.2 with https://github.com/numba/numba/pull/8414/files .

**Comment by esc** [comment]
That's all for now.
