### ISSUE TITLE
Numba 0.56.3 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#8502]
## numba 0.56.3

* [x] Cherry-pick items from the 0.56.3 milestone into a PR (#8505).
* [x] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY).
  * [x] Make, approve and merge a PR against the `main` branch (#8503).
  * [x] Create a cherry-pick from the merge and include in the cherry-pick-PR
    for the `release0.56` branch.
* [x] Check if any dependency pinnings need an update (e.g. NumPy)
* [x] Approve change log modifications and cherry-pick (#8504).
* [x] Merge change log modifications and cherry-picks to 0.56 release branch.
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed.
  * [x] Build farm CUDA testing has passed
* [x] Annotated tag 0.56.3 on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check `upload`).
* [x] Build wheels and sdist on the buildfarm (check "upload").
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`. https://anaconda.org/numba/numba/files?sort=basename&version=0.56.3&sort_order=desc
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`). https://pypi.org/project/numba/0.56.3/#files
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build. https://numba.readthedocs.io/en/0.56.3/
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers` (RC ONLY). https://numba.discourse.group/t/ann-numba-0-56-3/1600
* [x] Post link to python-announce-list@python.org.
* [x] Post link to Twitter. https://twitter.com/numba_jit

### Post release

* [x] Snapshot Build Farm config
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release. https://github.com/numba/numba/pull/8508
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY). https://github.com/numba/numba/releases/tag/0.56.3
* [x] Close milestone (and then close this release issue).
