### ISSUE TITLE
Meta Issue: NumPy Random Generator Support

### ISSUE THREAD

**Issue by kc611** [numba/numba#8519]
This issue page tracks the current progress of NumPy's random number generation support (the new `Generator` API) and links all related PRs and Issues. (This only links 'missing' features and not bug reports). 

Functionalities for core `Generator` support:
- [x] Core `Generator` boxing-unboxing.
- [ ] Constructors for `Generator` and `BitGenerator`
- [ ] Thread safety for `Generator` states.

Generator methods: (Methods that can be implemented right away are marked feasible)
- [x] numpy.random.Generator.integers
- [x] numpy.random.Generator.random
- [ ] numpy.random.Generator.choice (Depends on support for Advanced Indexing)
- [ ] numpy.random.Generator.bytes (Feasible, but no definitive return type in Numba)
- [x] numpy.random.Generator.shuffle
- [x] numpy.random.Generator.permutation
- [ ] numpy.random.Generator.permuted (Feasible)
- [x] numpy.random.Generator.beta
- [ ] numpy.random.Generator.binomial - https://github.com/numba/numba/pull/8371
- [x] numpy.random.Generator.chisquare
- [ ] numpy.random.Generator.dirichlet (Feasible)
- [x] numpy.random.Generator.exponential
- [x] numpy.random.Generator.f
- [x] numpy.random.Generator.gamma
- [x] numpy.random.Generator.geometric
- [ ] numpy.random.Generator.gumbel - https://github.com/numba/numba/pull/8232
- [ ] numpy.random.Generator.hypergeometric (Feasible, but large enough to require it's own PR)
- [x] numpy.random.Generator.laplace
- [x] numpy.random.Generator.logistic
- [x] numpy.random.Generator.lognormal
- [ ] numpy.random.Generator.logseries (Feasible)
- [ ] numpy.random.Generator.multinomial (Depends on #8371 )
- [ ] numpy.random.Generator.multivariate_hypergeometric (Feasible, but large enough to require it's own PR)
- [ ] numpy.random.Generator.multivariate_normal (Feasible)
- [x] numpy.random.Generator.negative_binomial
- [ ] numpy.random.Generator.noncentral_chisquare (Feasible)
- [ ] numpy.random.Generator.noncentral_f (Feasible)
- [x] numpy.random.Generator.normal
- [x] numpy.random.Generator.pareto
- [x] numpy.random.Generator.poisson
- [x] numpy.random.Generator.power
- [x] numpy.random.Generator.rayleigh
- [x] numpy.random.Generator.standard_cauchy
- [x] numpy.random.Generator.standard_exponential
- [x] numpy.random.Generator.standard_gamma
- [x] numpy.random.Generator.standard_normal
- [x] numpy.random.Generator.standard_t
- [x] numpy.random.Generator.triangular
- [x] numpy.random.Generator.uniform
- [ ] numpy.random.Generator.vonmises - https://github.com/numba/numba/pull/8232
- [x] numpy.random.Generator.wald
- [x] numpy.random.Generator.weibull
- [x] numpy.random.Generator.zipf

**Comment by maxnoe** [comment]
> numpy.random.Generator.choice (Depends on support for Advanced Indexing)

`choice` has one signature that is much easier to support: just giving an integer as first argument and it generating number with or without replacement up to not including that number.

```

In [1]: import numpy as np

In [2]: rng = np.random.default_rng(0)

In [3]: rng.choice(10, size=50, replace=True)
Out[3]: 
array([8, 6, 5, 2, 3, 0, 0, 0, 1, 8, 6, 9, 5, 6, 9, 7, 6, 5, 5, 9, 2, 8,
       6, 0, 3, 8, 5, 0, 7, 7, 8, 1, 0, 8, 0, 5, 0, 2, 4, 4, 4, 0, 0, 1,
       0, 6, 5, 6, 2, 6])

In [4]: rng.choice(100, size=50, replace=False)
Out[4]: 
array([28, 94, 97, 51, 56, 67, 81, 83, 59,  5, 80, 85, 44, 38, 27, 22, 93,
       95, 62, 58, 21, 36, 90, 64, 92, 46, 37, 61,  4, 49, 19, 74, 39, 35,
       72, 29, 66, 82, 54, 30, 63, 41, 24, 53, 89, 43, 42,  8, 88, 26])
```

That should be possible to support without any new fancy indexing support for numba, right?

I.e. `rng.choice(<int>)` is equivalent to `rng.choice(np.arange(<int>))`

**Comment by maxnoe** [comment]
It seems binomial support was added in #8371 so one more check could be marked above

**Comment by stuartarchibald** [comment]
Done, thanks @maxnoe .

**Comment by flying-sheep** [comment]
does anyone have a `.choice` implementation (with the int signature) that I can use today?

**Comment by maxnoe** [comment]
@flying-sheep We only needed the special case for two out of N without replacement:

```python
@njit(cache=not CTAPIPE_DISABLE_NUMBA_CACHE)
def choose_two_without_replacement(rng, n):
    values = np.empty(2, dtype=np.int64)

    # we need to draw two distinct integers in [0, n)
    # first sample can just be draw uniform:
    values[0] = rng.integers(0, n)
    # we draw the second sample in 0, n - 1 and shift by 1
    # if it's >= the first value, this means we draw uniform
    # in [0, ) with the exception of the first value
    values[1] = rng.integers(0, n - 1)
    if values[1] >= values[0]:
        values[1] += 1
    return values
```

**Comment by flying-sheep** [comment]
Thanks! I need an arbitrary number.

Weird that numba doesn’t support all Generator APIs, they’re all backed by native code that you can just call, right?

**Comment by flying-sheep** [comment]
here’s a simple version with no `p` support and only support for small `a` (as it allocates an array of that size).

Also maybe not ideal randomness guarantees.

```py
@overload_method(nb.types.NumPyRandomGeneratorType, "choice")
def NumPyRandomGeneratorType_choice(inst, a, size=None, replace=True):  # noqa: FBT002, N802
    if is_nonelike(size):
        def impl(inst, a, size=None, replace=True):  # noqa: FBT002
            return inst.integers(0, a)
    else:
        def impl(inst, a, size=None, replace=True):  # noqa: FBT002
            if replace:
                return inst.integers(0, a, size=size)
            else:
                pool = np.arange(a)
                for i in range(size):
                    j = inst.integers(i, a)
                    pool[i], pool[j] = pool[j], pool[i]
                return pool[:size].copy()
    return impl
```

**Comment by slayoo** [comment]
Hi!
` numpy.random.Generator.random()` lacks support for the `out` keyword enabling in-place operation.
here's a PR adding a mention about it to the docs: #10534 
HTH,
Sylwester
