### ISSUE TITLE
Numba 0.56.4 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#8561]
## numba 0.56.4

* [x] Cherry-pick items from the 0.56.4 milestone into a PR.
    * [x] https://github.com/numba/numba/pull/8537
* [x] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY).
  * [x] Make, approve and merge a PR against the `main` branch.
      * [x] https://github.com/numba/numba/pull/8552 
  * [x] Create a cherry-pick from the merge and include in the cherry-pick-PR
    for the `release0.56` branch.
* [x] Check if any dependency pinnings need an update (e.g. NumPy)
* [x] Approve change log modifications and cherry-pick.
    * [x] https://github.com/numba/numba/pull/8553
    * [x] #8571
* [x] Merge change log modifications and cherry-picks to `0.56` release branch.
    * [x] https://github.com/numba/numba/pull/8562 
    * [x] #8573
* [x] ~~Review, merge and check execution of release notebook. (FINAL ONLY)~~
* [x] FIXUP (see comments)
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed.
  * [x] Build farm CUDA testing has passed.
  * [x] Build farm Wheel build has passed
* [x] Annotated tag 0.56.4 on release branch (no `v` prefix). https://github.com/numba/numba/releases/tag/0.56.4
* [x] Build and upload conda packages on buildfarm (check `upload`).
* [x] Build wheels and sdist on the buildfarm (check "upload").
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`. https://anaconda.org/numba/numba/files?sort=basename&sort_order=desc&version=0.56.4
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi. https://pypi.org/project/numba/0.56.4/
* [x] Verify ReadTheDocs build. https://numba.readthedocs.io/en/0.56.4/
* [x] Post link to Twitter. https://twitter.com/numba_jit/status/1588512356815949824
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers` (RC ONLY). https://numba.discourse.group/t/ann-numba-0-56-4/1632
* [x] Post link to python-announce-list@python.org.

### Post release

* [x] Snapshot Build Farm config
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release. https://github.com/numba/numba/pull/8580
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY). https://github.com/numba/numba/releases/tag/0.56.4
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
During the buildout on the Anaconda build farm, some build issues arose and an additional patch was needed: https://github.com/numba/numba/pull/8570

**Comment by esc** [comment]
Note to self: add bullet to run the wheel build before tagging too.

**Comment by esc** [comment]
It's a wrap 🌯
