### ISSUE TITLE
Meta Issue: Support for Advanced/Fancy Indexing in Numba

### ISSUE THREAD

**Issue by kc611** [numba/numba#8616]
This issue page tracks the current progress of NumPy's Advanced / Fancy Indexing support and links all related PRs and Issues.

PRs related to Advanced Indexing support:

- [ ] Switching to a subspace-based logic at type level for NumPy array `getitem/setitem` methods. - https://github.com/numba/numba/pull/8238
- [ ] Add support for multidimensional indices. - https://github.com/numba/numba/pull/8491
- [ ] Add support for multiple array indices.
