### ISSUE TITLE
Housekeeping tasks for 0.57

### ISSUE THREAD

**Issue by sklam** [numba/numba#8762]
- [x] Need to move np baseline to 1.21. (xref: #8707)
- [x] Need to remove setuptools dep (https://github.com/numba/numba/pull/8476)
- [x] Need to deprecate pycc (xref: #8509, resolved by #8795)
- [ ] Need to sort out the code base because the tests are so noisy with deprecation warnings (#8674)

**Comment by sklam** [comment]
Didn't get to the last task:

- Need to sort out the code base because the tests are so noisy with deprecation warnings (https://github.com/numba/numba/pull/8674)

closing
