### ISSUE TITLE
Numba 0.57.0rc1 Checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#8841]
## Numba 0.57.0rc1

* [x] Merge to main.
    - [x] "remaining Pull-Requests from milestone".
      - [x] #8334
      - [x] #8870 
      - [x] #8879 
      - [x] #8880
      - [x] https://github.com/numba/numba/pull/8881
* [x] Check Numba's version support table documentation. Update via PR if
      needed.
* [x] Review deprecation schedule and notices. Make PRs if need be.
    - [x] #8864
    - [x] #8866
    - [ ] Any more?
* [x] Merge change log changes.
    - [x] #8869
* [x] Create 0.57 release branch.
* [x] Create PR against the release branch to make `numba/testing/main.py`
      to refer to `origin/release0.57` instead of `origin/main`. https://github.com/numba/numba/pull/8884
* [x] Dependency version pinning on release branch
  * [x] Pin llvmlite to `>=0.40.0rc1,<0.41.0`.
  * [x] Pin NumPy if needed (1.24?)
  * [x] Pin TBB if needed (no need; don't know what to pin as max)
  * https://github.com/numba/numba/pull/8884
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed. `numba_pynext_cpu_yaml_18` `numba_yaml_333`
  * [x] Build farm CUDA testing has passed.
  * [x] Build farm wheel testing has passed. `numba_wheel_78`
* [x] Annotated tag `0.57.0rc1` on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels and sdist on the buildfarm (check "upload").
  `numba_pynext_cpu_yaml_19`
   `numba_wheel_79`
   `numba_yaml_334`
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`. https://anaconda.org/numba/numba/files?version=0.57.0rc1
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi. https://pypi.org/project/numba/0.57.0rc1/
* [x] Initialize and verify ReadTheDocs build. (https://numba.readthedocs.io/en/0.57.0rc1/)
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers`.  https://numba.discourse.group/t/ann-numba-0-57-0rc1-and-llvmlite-0-40-0rc1/1879
* [ ] Post link to Twitter.

### Post Release:

* [x] Clean up `ci_artifacts` by moving files to sub-directories
* [x] Tag `0.58.0dev0` to start new development cycle on `main`.
* [x] Update llvmlite dependency via PR to `main`, PR includes version updates
      to: (https://github.com/numba/numba/pull/8916)
  * [x] `setup.py`
  * [x] `numba/__init__.py`
  * [x] `docs/environment.yml`
  * [x] `buildscripts/incremental/setup_conda_environment.sh`
  * [x] `buildscripts/incremental/setup_conda_environment.cmd`
  * [x] `buildscripts/condarecipe.local/meta.yaml`
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release (#8925).
* [ ] Close milestone (and then close this release issue).

**Comment by stuartarchibald** [comment]
Update for those subscribed to this ticket: as can be seen above by the list of remaining PRs to be merged from the milestone, Numba is very close to being ready to branch from `main` for the 0.57 release series. Unfortunately, in testing of `main` last night, the build farm reported an intermittent segmentation fault (segfault) in the test suite on a few of the test jobs. As a result, creating the release branch will be temporarily on hold whilst the cause of the segfault is investigated and hopefully fixed. Once resolved this ticket will be updated. Thank you for your patience and understanding.

**Comment by stuartarchibald** [comment]
It took a while to isolate this segfault (https://github.com/numba/numba/issues/8841#issuecomment-1492213902), due to it taking 20 minutes to (intermittently) reproduce it. Issue #8873 tracks the problem and contains debugging and discussion. An update will be posted once a decision is made about this issue.

**Comment by stuartarchibald** [comment]
Update: #8873 has been debugged, understood, and is hopefully fixed in #8879.

**Comment by egeres** [comment]
I don't want to disrespect the incredible work the numba developers are doing, but I find this meme so funny...

<img src="https://user-images.githubusercontent.com/8045792/230158618-8d36ede7-441e-4a8e-8e57-e4d2c6dc5f55.png" width="100%">

**Comment by OWKenobi** [comment]
thanks for fixing this!

from a noob point of view: how long from now on (rough estimate) till 0.57 will be available in the form of "pip install numba"?

**Comment by sklam** [comment]
RC1 wheels are posted. Use `pip install --pre numba`; or

```bash
pip install numba==0.57.0rc1
```

```
pip install llvmlite==0.40.0rc1
```
to get the specific versions exactly.

**Comment by sklam** [comment]
Conda packages are also available:

numba: https://anaconda.org/numba/numba/files?version=0.57.0rc1
llvmlite: https://anaconda.org/numba/llvmlite/files?version=0.40.0rc1

Installable with `conda install -c numba numba=0.57.0rc1`.

**Comment by slayoo** [comment]
FWIW, just reporting that `pip install --pre numba` gives us a valid installation on Linux and macOS with Pythons 3.7-3.11, while on Windows (Github Actions' `windows-latest`) it only works for Python 3.7, later versions seem to install OK, but when trying to `import numba`, there are the following errors:
```
   File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\numba\__init__.py", line 69, in <module>
    from numba.core import config
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\numba\core\config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\llvmlite\binding\__init__.py", line 4, in <module>
    from .dylib import *
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\llvmlite\binding\dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\llvmlite\binding\ffi.py", line 187, in <module>
    raise OSError(msg)
OSError: Could not find/load shared object file: llvmlite.dll
 Error was: Could not find module 'C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\llvmlite\binding\llvmlite.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
(see: https://github.com/numba-mpi/numba-mpi/actions/runs/4645911575/jobs/8222023577?pr=46)

**Comment by ldeluigi** [comment]
I can confirm the issue on Windows 10

**Comment by Alpengreis** [comment]
I have the same problem as @slayoo on Win 10 with Python 3.11.3 ...

**Comment by sklam** [comment]
Thanks for the report for the windows issue and the confirmation of the issues. I'm debugging it now.

**Comment by sklam** [comment]
The windows issue is llvmlite specific and is very likely another case of https://github.com/numba/llvmlite/issues/650.
I have tested the wheels in a windows machine but it works fine. This indicates that it is likely a dependency problem. I'm trying to get a vanilla windows to test what it's missing. My current guess is that it requires the C++ redistributable package (see https://github.com/numba/llvmlite/issues/650#issuecomment-768706785).

**Comment by ldeluigi** [comment]
I installed the C++ redistributable but the problem still occurs

**Comment by sklam** [comment]
On a vanilla windows with python installed from python.org, I can replicate the llvmlite error. To fix it, I need to install [C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) and copy a `zlib.dll` next to the `llvmlite.dll` (as mentioned in https://github.com/numba/llvmlite/issues/650#issuecomment-747252728). I got the `zlib.dll` from miniconda. For conda users, this can be fixed by `conda install zlib`.

**Comment by Alpengreis** [comment]
@sklam 

Had installed the related C++ Redistrutable already. Then I copied a zlib.dll next to llmite.dll. It still doesn't work ...

**Comment by eriknw** [comment]
I am finding that numba 0.57.0rc1 segfaults on Windows when installed with pip or conda for the following:
```python
import numpy as np
from numba import njit

f = njit(lambda x: np.exp2(x))
f(np.int8(2))
```
I create the environments via
```
conda create -n py310pip -c conda-forge python=3.10
pip install numba==0.57.0rc1
```
and
```
conda create -n py310conda -c numba -c conda-forge python=3.10 numba
```
I have not found any other function for which this occurs.

I discovered this when testing [`python-graphblas`](https://github.com/python-graphblas/python-graphblas/issues/431). Here's an example traceback:
<details>
<summary>LLVM ERROR: Symbol not found: ldexpf</summary>

```
LLVM ERROR: Symbol not found: ldexpf
Fatal Python error: Aborted

Current thread 0x00000bb0 (most recent call first):
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\llvmlite\binding\ffi.py", line 152 in __call__
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\llvmlite\binding\executionengine.py", line 92 in finalize_object
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\numba\core\codegen.py", line 1060 in wrapper
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\numba\core\codegen.py", line 999 in _finalize_specific
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\numba\core\codegen.py", line 797 in _finalize_final_module
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\numba\core\codegen.py", line 765 in finalize
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\numba\core\codegen.py", line 567 in _ensure_finalized
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\numba\core\codegen.py", line 989 in get_pointer_to_function
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\numba\core\ccallback.py", line 75 in compile
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\numba\core\compiler_lock.py", line 35 in _acquire_compile_lock
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\numba\core\decorators.py", line 311 in wrapper
  File "D:\a\python-graphblas\python-graphblas\graphblas\core\operator\unary.py", line 235 in _build
  File "D:\a\python-graphblas\python-graphblas\graphblas\core\operator\unary.py", line 305 in register_new
  File "D:\a\python-graphblas\python-graphblas\graphblas\unary\numpy.py", line 152 in __getattr__
  File "D:\a\python-graphblas\python-graphblas\graphblas\tests\test_numpyops.py", line 83 in test_npunary
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\python.py", line 194 in pytest_pyfunc_call
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\python.py", line 1799 in runtest
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\runner.py", line 169 in pytest_runtest_call
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\runner.py", line 262 in <lambda>
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\runner.py", line 341 in from_call
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\runner.py", line 261 in call_runtest_hook
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\runner.py", line 222 in call_and_report
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\runner.py", line 133 in runtestprotocol
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\runner.py", line 114 in pytest_runtest_protocol
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\main.py", line 348 in pytest_runtestloop
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\main.py", line 323 in _main
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\main.py", line 269 in wrap_session
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\main.py", line 316 in pytest_cmdline_main
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\config\__init__.py", line 166 in main
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\_pytest\config\__init__.py", line 189 in console_main
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\pytest\__main__.py", line 5 in <module>
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\coverage\execfile.py", line 199 in run
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\coverage\cmdline.py", line 830 in do_run
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\coverage\cmdline.py", line 659 in command_line
  File "C:\Miniconda3\envs\graphblas\lib\site-packages\coverage\cmdline.py", line 943 in main
  File "C:\Miniconda3\envs\graphblas\Scripts\coverage-script.py", line 10 in <module>
graphblas/tests/test_numpyops.py::test_npunary 
```

</details>

**Comment by sklam** [comment]
@maxnoe, Thank you for testing the RC.

**Comment by oyvindln** [comment]
Also FYI Ubuntu 23.04 released with a version of numba 0.56 with changes for Python 3.11 support backported. Whether it's 100% stable I don't know.

http://changelogs.ubuntu.com/changelogs/pool/universe/n/numba/numba_0.56.4+dfsg-2/changelog

**Comment by benz0li** [comment]
@numba @stuartarchibald et al.: Thank you for all the hard work.

**Comment by stuartarchibald** [comment]
> @numba @stuartarchibald et al.: Thank you for all the hard work.

@benz0li thank you for your kind words of support for the Numba folks, they are much appreciated!
