### ISSUE TITLE
Numba 0.57.0 Checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#8921]
## numba 0.57.0

* [x] Cherry-pick items from the 0.57.0 milestone into a PR.
    * [x] https://github.com/numba/numba/pull/8922
* [x] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY).
  * [x] Make, approve and merge a PR against the `main` branch (#8929).
  * [x] Create a cherry-pick from the merge and include in the cherry-pick-PR
    for the `release0.57` branch.
* [x] Check if any dependency pinnings need an update (e.g. NumPy)
   * [x] From OOB discussion between @sklam and @stuartarchibald, this seems ok, `setup.py`, `meta.yaml` and `__init__.py` seem to have NumPy, Python and TBB selected appropriately.
* [x] Approve change log modifications and cherry-pick (#8929).
* [x] Merge change log modifications and cherry-picks to X.Y release branch.
  * [x] https://github.com/numba/numba/pull/8922
* [x] Changelog date fix https://github.com/numba/numba/pull/8932 
    * [x] cherrypick to release branch: https://github.com/numba/numba/pull/8935
* [x] ~Review, merge and check execution of release notebook. (FINAL ONLY)~
* ~[ ] Run the HEAD of the release branch through the build farm and confirm:~
  * ~[ ] Build farm CPU testing has passed.~
  * ~[ ] Build farm CUDA testing has passed~
  * ~[ ] Build farm wheel testing has passed~
* [x] Annotated tag 0.57.0 on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check `upload`). `numba_yaml_346` `numba_pynext_cpu_yaml_23`
* [x] Build wheels and sdist on the buildfarm (check "upload"). `numba_wheel_81`
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi. `https://pypi.org/project/numba/0.57.0/`
* [x] Verify ReadTheDocs build.
* [x] Post link to Twitter. https://twitter.com/numba_jit/status/1653448978430558218
* [x] Post announcement to discourse group ~and ping the release testers group
  using `@RC_Testers` (RC ONLY).~ https://numba.discourse.group/t/ann-numba-0-57-0-and-llvmlite-0-40-0/1914
* [x] Post link to python-announce-list@python.org.

### Post release

* [x] Snapshot Build Farm config
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
* [x] Close milestone (and then close this release issue).

**Comment by catap** [comment]
Hey,

Any plans to release it soon?
