### ISSUE TITLE
Checklist of deferred items from Advanced Indexing PRs

### ISSUE THREAD

**Issue by kc611** [numba/numba#8941]
As titled, 

This PR highlights items that were discovered during the PR review process of #8491 but were deferred to subsequent PRs because their scope exceeds a single PR:

- [ ] Testing/investigating indexing failures in cases where NRT is not available in context (for instance CUDA) (See https://github.com/numba/numba/pull/8491#discussion_r1185176323)
- [ ] Investigate in what cases, in practice, do Numba array constructs share memory and how does it affect Advanced Indexing (See https://github.com/numba/numba/pull/8491#discussion_r1185184606)
- [ ] The functions `flat_imp_copy` and `flat_imp_nocopy` being used in Advanced Indexing implementations need to moved to a global level  to avoid recompilation every time advanced indexing is invoked.  (See https://github.com/numba/numba/pull/8491#discussion_r1181704457)
- [ ] During testing of Advanced Indexing, the arrays that are differently ordered in NumPy won't necessarily be classified as the same order in Numba, so that needs an appropriate fix to make sure we're testing for differently ordered arrays as required. (See https://github.com/numba/numba/pull/8491#discussion_r1185200793)

**Comment by sklam** [comment]
Additional advance indexing features to consider:

- [ ] Support optional index as described in [this comment (pt. 1)](https://github.com/numba/numba/pull/7980#issuecomment-1524094669)
