### ISSUE TITLE
Numba 0.57.1-rc1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#9000]
## numba 0.57.1-rc1

* [x] Cherry-pick items from the 0.57.1-rc1 milestone into a PR.

Non cherry-picked issues, these are issues that have not been cherry-picked yet individually and so they need to become part of the cherry-pick PR.

Issue |PR    |Merge
------|------|----------
#8940 |#8958 |0c8b59e106
#8940 |#8996 |0c752441b3
#8936 |#8947 |ec09902714
#8939 |#8998 |24c89c25dd
#8967 |#8982 |dd082ca031
#8949 |#8965 |bca99bcde4
#8951 |#8964 |98ab12e35c
None  |#9004 |5f1ea887113
None  |#9006 |9710916650
None  |#9005. |c9cc06ba141

Issues that have already been cherry-picked. These have had the author create individual cherry-pick PRs, so they do not need to be included in the cherry-pick PR, but they DO need to mentioned in the change log.

Issue |PR    |Cherry
------|------|------
#8994 |#None |#None
#8977 |#8978 |#8991
#8888 |#8895 |#8968
#None |#8976 |#8979

Cherry-pick PR is now: https://github.com/numba/numba/pull/9003

* [x] Update the "version support table" in the documentation with the final
  release date .
  * [ ] <strike>Make, approve and merge a PR against the `main` branch.</strike>
  * [ ] <strike>Create a cherry-pick from the merge and include in the cherry-pick-PR</strike>
    for the `release0.57` branch.</strike?
  * [x] add to cherry-pick PR.
* [x] Check if any dependency pinnings need an update (e.g. NumPy) and update on cherry-pick branch.
* [ ] <strike>Approve change log modifications and cherry-pick.</strike>
* [x] Add changelog modifications to cherry-pick PR.
* [x] Merge change log modifications and cherry-picks to 0.57 release branch.
  * [x] https://github.com/numba/numba/pull/9003
* [ ] <strike>Review, merge and check execution of release notebook. (FINAL ONLY)</strike>
* [x] Run the HEAD of the release branch through the build farm and confirm: (pre-tag testing)
  * [x] Build farm CPU testing has passed. (`numba_yamla_363`)
  * [x] Build farm CUDA testing has passed (`numba_smoketest_cuda_yaml_203`)
  * [x] Build farm wheel testing has passed (`numba_wheel_83`)
* [x] Annotated tag 0.57.1rc1 on release branch (no `v` prefix).
  * [x] https://github.com/numba/numba/releases/tag/0.57.1rc1
* [x] Build and upload conda packages on buildfarm (check `upload`).
  * [x] `numba_yaml_364`
* [x] Build wheels and sdist on the buildfarm (check "upload").
  * [x] `numba_wheel_84` 
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
    * [x] https://anaconda.org/numba/numba/files?sort=basename&sort_order=desc&version=0.57.1rc1
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
    * [x] https://pypi.org/project/numba/0.57.1rc1/#files 
* [x] Verify ReadTheDocs build.
    * [x] https://numba.readthedocs.io/en/0.57.1rc1/
* [x] Post link to Twitter.
    * [x] https://twitter.com/numba_jit/status/1668302764659683351
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers` (RC ONLY).
    * [x] https://numba.discourse.group/t/ann-numba-0-57-1rc1/1986
* [ ] <strike>Post link to python-announce-list@python.org.</strike>

### Post release

* [x] Snapshot Build Farm config
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
  * [x] https://github.com/numba/numba/pull/9021
* [ ] <strike>Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).</strike>
* [ ] <strike>Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).</strike>
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
For this release, as a release manager, I have taken the executive decision to make the changelog and version support table updates on the `release` branch and to then cherry-pick them back onto `main` -- contrary to what is listed in the checklist.  I have taken this decision because it's much easier that way, in case additional things need adding or changing during the release process. We basically circumvent the process of making a PR to `main` (say to change the date of the release), having to get that approved, merged and cherry-picked onto the `release` branch. Instead we can just craft the release using PRs that target the release branch, and then cherry pick change-log updates and version support updates onto `main` once the final patch release is out. I'll update the checklist post-release as usual.

**Comment by esc** [comment]
Note about checklist updates:

* The whole way we provide change-log modifications and version support table updates will need to be revised.

**Comment by esc** [comment]
We should add the exact `git tag` command to the checklist, such that it can be copied and pasted into the terminal. Otherwise we will always get potentially inconsistent tags.

**Comment by esc** [comment]
Question about:

```
 Verify packages uploaded to Anaconda Cloud and move to
numba/label/main.
```

Does "move" in this context mean: place in new location and delete at old one, or does it mean "copy"? Looking at previous releases, we probably mean copy. The bullet must be disambiguated and updated to describe what needs doing in a less contextual way.

**Comment by esc** [comment]
That's it for now.
