### ISSUE TITLE
Numba 0.57.1 Checklist (FIXME)

### ISSUE THREAD

**Issue by esc** [numba/numba#9023]
## numba 0.57.1

* [ ] Cherry-pick items from the 0.57.1 milestone into a PR.
* [ ] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY).
  * [ ] Make, approve and merge a PR against the `main` branch.
  * [ ] Create a cherry-pick from the merge and include in the cherry-pick-PR
    for the `release0.57` branch.
* [ ] Check if any dependency pinnings need an update (e.g. NumPy)
* [ ] Approve change log modifications and cherry-pick.
* [ ] Merge change log modifications and cherry-picks to 0.57 release branch.
  * [ ] https://github.com/numba/numba/pull/XXXX
* [ ] Review, merge and check execution of release notebook. (FINAL ONLY)
* [ ] Run the HEAD of the release branch through the build farm and confirm:
  * [ ] Build farm CPU testing has passed.
  * [ ] Build farm CUDA testing has passed
  * [ ] Build farm wheel testing has passed
* [ ] Annotated tag 0.57.1 on release branch (no `v` prefix).
* [ ] Build and upload conda packages on buildfarm (check `upload`).
* [ ] Build wheels and sdist on the buildfarm (check "upload").
* [ ] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [ ] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [ ] Verify wheels for all platforms arrived on PyPi.
* [ ] Verify ReadTheDocs build.
* [ ] Post link to Twitter.
* [ ] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers` (RC ONLY).
* [ ] Post link to python-announce-list@python.org.

### Post release

* [ ] Snapshot Build Farm config
* [ ] Clean up `ci_artifacts` by moving files to subdirectories
* [ ] Update release checklist template with any additional bullet points that
      may have arisen during the release.
* [ ] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [ ] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
* [ ] Close milestone (and then close this release issue).

**Comment by esc** [comment]
closing again, will re-open after merge of https://github.com/numba/numba/pull/9021
