### ISSUE TITLE
Numba 0.57.1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#9024]
## numba 0.57.1

* [ ] <strike>Cherry-pick items from the 0.57.1 milestone into a cherry-pick PR.</strike> (no items to cherry-pick)
* [x] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY) and add to cherry-pick PR
* [x] Update `CHANGE_LOG` on cherry-pick PR
* [x] Check if any dependency pinnings need an update (e.g. NumPy)
* [x] Approve cherry-pick PR
* [x] Merge cherry-pick PR to 0.57 release branch.
  * [x] https://github.com/numba/numba/pull/9026
* [ ] <strike>Review, merge and check execution of release notebook. (FINAL ONLY)</strike> (no release notebook, it's a patch release)
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed. `numba_yaml_366`
  * [x] Build farm CUDA testing has passed. `numba_smoketest_cuda_yaml_206`
  * [x] Build farm wheel testing has passed. `numba_wheel_85`
* [x] Annotated tag 0.57.1 on release branch (no `v` prefix).
  `git tag -am "Version 0.57.1" 0.57.1`
  * [x] https://github.com/numba/numba/releases/tag/0.57.1
* [x] Build and upload conda packages on buildfarm (check `upload`).
  * [x] `numba_yaml_367`
* [x] Build wheels and sdist on the buildfarm (check "upload").
  * [x] `numba_wheel_86`
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
  * [x] https://anaconda.org/numba/numba/files?sort=basename&sort_order=desc&version=0.57.1
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
  * [x] https://pypi.org/project/numba/0.57.1/ 
* [x] Verify ReadTheDocs build.
  * [x] https://numba.readthedocs.io/en/0.57.1/ 
* [x] Post link to Twitter.
  * [x] https://twitter.com/numba_jit/status/1671577594586644480
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers` (RC ONLY).
  * [x] https://numba.discourse.group/t/ann-llvmlite-0-40-1/1995
* [x] Post link to python-announce-list@python.org.

### Post release

* [x] Cherry-pick change-log and version support table modifications to `main`
  * [x] https://github.com/numba/numba/pull/9046
* [x] Snapshot Build Farm config
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [ ] <strike>Update release checklist template with any additional bullet points that
      may have arisen during the release.</strike> none needed
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
  * [x] https://github.com/numba/numba/releases/tag/0.57.1 
* [ ] Close milestone (and then close this release issue).

**Comment by esc** [comment]
> Sorry guys but... Is this finished or hanging, for some reason?
> 
> Version 0.57.1 as been tagged but latest is still pointing to 0.57.0...

Which `latest` is this?

**Comment by ZupoLlask** [comment]
Sorry, what I intended to recall is that here, in Github, latest version `0.57.1` is not yet released.

![image](https://github.com/numba/numba/assets/1229716/0388678f-c8a9-42de-9c16-542dcc8ca38d)

**Comment by esc** [comment]
@ZupoLlask yes, this is a post-release action:

```
 Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
```

Perhaps it ought to be part of the release actions, rather than post-release ones.

In any case, thank you for asking: it is fixed now: https://github.com/numba/numba/releases/tag/0.57.1
