### ISSUE TITLE
Numba 0.58.0-rc1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/numba#9122]
## Numba 0.58.0

* [x] Merge to `main`.
    - [x] ["remaining Pull-Requests from milestone".](https://github.com/numba/numba/milestone/69)
* [ ] Check Numba's version support table documentation. Update via PR if
      needed.
* [x] <strike>Review deprecation schedule and notices. Make PRs if need be.</strike> none were needed
* [x] Merge change log changes.
    - [x] "PR with changelog entries". https://github.com/numba/numba/pull/9137
    - [ ] Check missing towncrier news fragments with https://github.com/numba/numba/pull/9101#issuecomment-1675068409
* [x] Create `0.58` release branch. https://github.com/numba/numba/tree/release0.58
* [x] Create PR against the release branch to make `numba/testing/main.py`
      to refer to `origin/release0.58` instead of `origin/main`.
* [x] Dependency version pinning on release branch
  * [x] Pin llvmlite to `0.41.*`.
  * [x] Pin NumPy if needed
  * [ ] <strike>Pin TBB if needed</strike>
* [x] Do the above in a release actions PR: https://github.com/numba/numba/pull/9138 
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed. `numba_yaml_390`
  * [x] Build farm CUDA testing has passed. `numba_cuda_smoketest_yaml_216`
  * [x] Build farm wheel testing has passed. `numba_wheel_87`
* [x] Annotated tag `0.58.0rc1` on release branch (no `v` prefix). https://github.com/numba/numba/tree/0.58.0rc1
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels and sdist on the buildfarm (check "upload").
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
  * [x] https://anaconda.org/numba/numba/files?version=0.58.0rc1 
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
  * [x] https://pypi.org/project/numba/0.58.0rc1/#files 
* [x] Initialize and verify ReadTheDocs build.
  * [x] https://numba.readthedocs.io/en/0.58.0rc1/
* [x] Post announcement to discourse group and ping the release testers group using `@RC_Testers`.
  * [x] https://numba.discourse.group/t/ann-numba-0-58-0rc1-and-llvmlite-0-41-0rc1/2078
* [x] Post link to X.
  * [x] https://twitter.com/numba_jit/status/1692515785976041763 

### Post Release:

* [x] Clean up `ci_artifacts` by moving files to sub-directories
* [x] Tag `0.59.0dev0` to start new development cycle on `main`.
  * [x] https://github.com/numba/numba/releases/tag/0.59.0dev0 
* [x] Update llvmlite dependency via PR to `main`, PR includes version updates
      to:
  * [x] `setup.py`
  * [x] `numba/__init__.py`
  * [x] `docs/environment.yml`
  * [x] `buildscripts/incremental/setup_conda_environment.sh`
  * [x] `buildscripts/incremental/setup_conda_environment.cmd`
  * [x] `buildscripts/condarecipe.local/meta.yaml`
  * [ ] https://github.com/numba/numba/pull/9148
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
  * [x] https://github.com/numba/numba/pull/9149
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Note to self: twitter is now called X

**Comment by esc** [comment]
it's a wrap
