### ISSUE TITLE
Numba 0.58.0rc2 Checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#9160]
## numba 0.58.0rc2

* [x] Cherry-pick items from the 0.58.0rc2 milestone into a cherry-pick PR.
    * [x] https://github.com/numba/numba/pull/9183
* ~[ ] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY) and add to cherry-pick PR~
* [x] Update `CHANGE_LOG` on cherry-pick PR https://github.com/numba/numba/pull/9183/commits/f50d3c300c591b3ae575af8dfcd1f0f35143451c
    * [x] [update release note in the docs](https://github.com/numba/numba/pull/9158/files#diff-a657448c4534369799480ca9a7f2d55a62a74892a1b2b3b2b73ad581aeb5d452R11)
* [x] Check if any dependency pinnings need an update (e.g. NumPy)
* [x] Approve cherry-pick PR
* [x] Merge cherry-pick PR to 0.58 release branch.
  * [ ] https://github.com/numba/numba/pull/XXXX
* ~[ ] Review, merge and check execution of release notebook. (FINAL ONLY)~
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed.
  * [x] Build farm CUDA testing has passed
  * [x] Build farm wheel testing has passed
* [x] Annotated tag 0.58.0rc2 on release branch (no `v` prefix).
  `git tag -am "Version 0.58.0rc2" 0.58.0rc2
* [x] Build and upload conda packages on buildfarm (check `upload`). `numba_yaml_396`
* [x] Build wheels and sdist on the buildfarm (check "upload"). `numba_wheel_91`
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
* [ ] Post link to X and to Mastodon and...
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers` (RC ONLY).
* [ ] Post link to python-announce-list@python.org.

### Post release

* [ ] Cherry-pick change-log and version support table modifications to `main`
* [ ] Snapshot Build Farm config
* [ ] Clean up `ci_artifacts` by moving files to subdirectories
* [ ] Update release checklist template with any additional bullet points that
      may have arisen during the release.
* [ ] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [ ] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
* [x] Close milestone (and then close this release issue).
