### ISSUE TITLE
Tracking NumPy usage in various modules. 

### ISSUE THREAD

**Issue by kc611** [numba/numba#9193]
## Feature request

As titled, this PR tracks usage of NumPy across Numba. The end goal is to hopefully refactor NumPy usage in a way such that it is restricted to either `numba.np`  and/or `numba.cuda` module in order to simplify dependencies.

Following are places other than `numba.np` where NumPy is being used:
- [ ] `numba.core`
  - [ ] `boxing.py` (Will require type separation between NumPy and Python scalar types.)
  - [ ] `errors.py`
  - [ ] `inline_closurecall.py`
  - [ ] `ir_utils.py`
  - [ ] `utils.py`
  - [ ] `datamodel.models.py`
  - [ ] `types` module (Will require type separation between NumPy and Python scalar types.)
  - [ ] `typing` module (Will require type separation between NumPy and Python scalar types.)
- [ ] `numba.cpython`
  - [ ] `builtins.py`
  - [ ] `charseq.py`
  - [ ] `hashing.py`
  - [ ] `mathimpl.py`
  - [ ] `numbers.py`
  - [ ] `randomimpl.py`
  - [ ] `unicode_support.py`
  - [ ] `unicode.py`
- [ ] `numba.misc`
  - [ ] `dummyarray.py`
  - [ ] `gdb_print_extension.py`
  - [ ] `mergesort.py`
  - [ ] `numba_gdbinfo.py`
  - [ ] `numba_sysinfo.py`
  - [ ] `quicksort.py`
  - [ ] `special.py`

For the `.parfors`, `.stencils` and `.pycc`modules, they can be considered their own separate specialized modules depending on the `numba.np` module.
