### ISSUE TITLE
Numba 0.58.0 Checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#9194]
## numba 0.58.0

* [x] Cherry-pick items from the 0.58.0 milestone into a cherry-pick PR.
  * [x] https://github.com/numba/numba/pull/9190 
* [x] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY) and add to cherry-pick PR
* [x] Update `CHANGE_LOG` on cherry-pick PR
* [x] <strike>Check if any dependency pinnings need an update (e.g. NumPy)</strike>
* [x] Approve cherry-pick PR https://github.com/numba/numba/pull/9203
* [x] Merge cherry-pick PR to `release0.58` release branch.
* [ ] <strike>Review, merge and check execution of release notebook. (FINAL ONLY)</strike>
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed (`numba_yaml_399`)
  * [x] Build farm CUDA testing has passed (`numba_smoketest_cuda_yaml_218`)
  * [x] Build farm wheel testing has passed (`numba_wheel_92`)
* [x] Annotated tag 0.58.0 on release branch (no `v` prefix). `git tag -am "Version 0.58.0" 0.58.0`
  * [x] https://github.com/numba/numba/releases/tag/0.58.0
* [x] Build and upload conda packages on buildfarm (check `upload`). (`numba_yaml_400`)
* [x] Build wheels and sdist on the buildfarm (check "upload"). (`numba_wheel_93`)
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
  * [x] https://anaconda.org/numba/numba/files?sort=basename&sort_order=desc&version=0.58.0 
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
  * [x] https://pypi.org/project/numba/0.58.0/#files
* [x] Verify ReadTheDocs build.
  * [x] https://numba.readthedocs.io/en/0.58.0/ 
* [x] Post link to X and to Mastodon and...
  * [x] https://twitter.com/numba_jit/status/1704822285301911668 
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers` (RC ONLY).
  * [x] https://numba.discourse.group/t/ann-numba-0-58-0-and-llvmlite-0-41-0/2148
* [x] Post link to python-announce-list@python.org.

### Post release

* [x] Cherry-pick change-log and version support table modifications to `main`
  * [x] https://github.com/numba/numba/pull/9205 
* [x] Snapshot Build Farm config
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [ ] <strike>Update release checklist template with any additional bullet points that
      may have arisen during the release.</strike> to be done for 0.58.1
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
  * [x] https://github.com/numba/numba/releases/tag/0.58.0 
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
The tag command needs an additional backtick. `\``

**Comment by esc** [comment]
> The tag command needs an additional backtick.

This will be completed as part of https://github.com/numba/numba/issues/9238
