### ISSUE TITLE
Numba 0.58.1 Checklist 

### ISSUE THREAD

**Issue by esc** [numba/numba#9238]
## numba 0.58.1

* [x] Cherry-pick items from the 0.58.1 milestone into a cherry-pick PR.
* [x] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY) and add to cherry-pick PR
* [x] Update `CHANGE_LOG` on cherry-pick PR (Did the `towncrier` dance instead, checklist needs an update.
* [x] Check if any dependency pinnings need an update (e.g. NumPy)
* [x] Approve cherry-pick PR
* [x] Merge cherry-pick PR to 0.58 release branch.
  * [x] https://github.com/numba/numba/pull/9240
* [ ] <strike>Review, merge and check execution of release notebook. (FINAL ONLY)</strike>
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed. (`numba_yaml_404 `)
  * [x] Build farm CUDA testing has passed (`numba_smoketest_cuda_yaml_220 `)
  * [x] Build farm wheel testing has passed (`numba_wheel_94 `)
* [x] Annotated tag 0.58.1 on release branch (no `v` prefix).
  `git tag -am "Version 0.58.1" 0.58.1`
  * [x] https://github.com/numba/numba/releases/tag/0.58.1
* [x] Build and upload conda packages on buildfarm (check `upload`).
  * [x] `numba_yaml_405` 
* [x] Build wheels and sdist on the buildfarm (check "upload").
  * [x] `numba_wheel_95`
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
  * [x] https://anaconda.org/numba/numba/files?sort=basename&sort_order=desc&version=0.58.1# 
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
  * [x] https://pypi.org/project/numba/0.58.1/#files 
* [x] Verify ReadTheDocs build.
  * [x] https://numba.readthedocs.io/en/0.58.1/ 
* [x] Post link to X and to Mastodon and...
  * [x] https://twitter.com/numba_jit/status/1714647834329276674 
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers` (RC ONLY).
  * [x] https://numba.discourse.group/t/ann-numba-0-58-1-and-llvmlite-0-41-1/2219
* [ ] Post link to python-announce-list@python.org.

### Post release

* [x] Cherry-pick change-log and version support table modifications to `main`
  * [x] https://github.com/numba/numba/pull/9301 
* [x] Snapshot Build Farm config
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
  * [x] https://github.com/numba/numba/pull/9302
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
  * [x] https://github.com/numba/numba/releases/tag/0.58.1 
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Only two minor PRs to review and merge to get this one closed out too.
