### ISSUE TITLE
Numba 0.59.0rc1 Checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#9370]
## Numba 0.59.0rc1

* [x] Merge to main.
    - [x] #9362 
    - [ ] anything else?
* [x] Check Numba's version support table documentation. Update via PR if
      needed.
* [x] Review deprecation schedule and notices. Make PRs if need be.
* [x] Merge change log changes.
    - [x] PR with changelog entries: #9368
* [x] Create 0.59 release branch.
* [x] Create PR against the release branch to make `numba/testing/main.py`
      to refer to `origin/release0.59` instead of `origin/main`.
* [x] Dependency version pinning on release branch
  * [x] Pin llvmlite to `0.42.*`.
  * [x] Pin NumPy if needed
  * [x] ~Pin TBB if needed~ not needed
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed.
  * [x] Build farm CUDA testing has passed.
  * [x] Build farm wheel testing has passed.
* [x] Annotated tag `0.59.0rc1` on release branch (no `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload"). `numba_yaml_424`
* [x] Build wheels and sdist on the buildfarm (check "upload"). `numba_wheel_100`
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Initialize and verify ReadTheDocs build.
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers`.
* [x] Post link to X and to Mastodon and...
  * [x] X https://twitter.com/numba_jit/status/1745099594692714987 

### Post Release:

* [x] Clean up `ci_artifacts` by moving files to sub-directories
* [x] Tag `0.60.0dev0` to start new development cycle on `main`.
* [x] Update llvmlite dependency via PR to `main`, PR includes version updates
      to: https://github.com/numba/numba/pull/9425
  * [x] `setup.py`
  * [x] `numba/__init__.py`
  * [x] `docs/environment.yml`
  * [x] `buildscripts/incremental/setup_conda_environment.sh`
  * [x] `buildscripts/incremental/setup_conda_environment.cmd`
  * [x] `buildscripts/condarecipe.local/meta.yaml`
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
* [x] Close milestone (and then close this release issue).
