### ISSUE TITLE
New Type System/NumPy 2 support tracking

### ISSUE THREAD

**Issue by kc611** [numba/numba#9409]
This issue page tracks the progress of NumPy 2 development and consequently the development of a new type system alongside it for making it possible. Following are a list of tasks to be accomplished:

- [ ] Adding a new type system implementation capable of distinguishing between NumPu and Python scalars to be able to apply casting rules defined by NumPy 2.
  - [ ] Adding new types for scalars and isolating old types from the implementations. (https://github.com/numba/numba/pull/9408)
  - [ ] Isolating and aliasing the type initialiations across Numba.
  - [ ] Adding templates for new type system
- [ ] Abstracting out the typecasting rules to be able to manage multiple sets of independent type casting rules. (Determined by config flags)
    - [ ] Adding NumPy 2 casting rules as one of the possible set of casting rules.
