### ISSUE TITLE
Numba 0.59.1 Checklist

### ISSUE THREAD

**Issue by sklam** [numba/numba#9485]
## numba 0.59.1

* [x] Cherry-pick items from the 0.59.1 milestone into a cherry-pick PR.
* [x] Update the "version support table" in the documentation with the final
  release date (FINAL ONLY) and add to cherry-pick PR
* [x] Update `CHANGE_LOG` on cherry-pick PR
* [x] Check if any dependency pinnings need an update (e.g. NumPy) NO NEED
* [x] Cherrypick #9491 and update changelog
* [x] Approve cherry-pick PR
* [x] Merge cherry-pick PR to 0.59.1 release branch.
  * [x] https://github.com/numba/numba/pull/9480
* ~[ ] Review, merge and check execution of release notebook. (FINAL ONLY)~
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed. `numba_yaml_441`
  * [x] Build farm CUDA testing has passed. `numba_yaml_441`
  * [x] Build farm wheel testing has passed `numba_wheel_104`
* [x] Annotated tag 0.59.1 on release branch (no `v` prefix).
  `git tag -am "Version 0.59.1" 0.59.1`
* [x] Build and upload conda packages on buildfarm (check `upload`).  `numba_yaml_442`
* [x] Build wheels and sdist on the buildfarm (check "upload"). `numba_wheel_105`
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`.
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
* [x] Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).
* [x] Post link to X and to Mastodon and...
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers` (RC ONLY). https://numba.discourse.group/t/ann-numba-0-59-1/2473
* [x] Post link to python-announce-list@python.org.

### Post release

* [x] Cherry-pick change-log and version support table modifications to `main` (https://github.com/numba/numba/pull/9502)
* [x] Cherry-pick other changes: See TODO in https://github.com/numba/numba/pull/9480#issue-2174363830 (https://github.com/numba/numba/pull/9502)
* [x] Snapshot Build Farm config (no changes)
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Close milestone (and then close this release issue).

**Comment by tasansal** [comment]
Hi Numba team,

I came here because I was searching for 0.59.1 issues installing via `conda`. 

My (linux) conda-forge CI fails because conda can't find 0.59.1 on the main channel [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=901762&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3). I can also replicate the issues on a Windows (x86-64) machine running Python 3.12. Am I doing something wrong?

```console
$ conda create -n numba python=3.12
$ conda activate numba
$ conda install numba=0.59.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - numba=0.59.1
```

Based on the below, it does seem like its there, but its not installable. Any ideas?

![image](https://github.com/numba/numba/assets/13684161/499c6a1e-3c69-4c53-822f-0e63a3cb20cb)
![image](https://github.com/numba/numba/assets/13684161/df075bec-eb1c-444f-b8ec-86e70dddea39)

**Comment by sklam** [comment]
0.59.1 is published on conda default channel now.
