### ISSUE TITLE
Numba 0.60.0rc1 Checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#9544]
## Numba 0.60.0rc1

* [x] Merge to main.
    - [x] #9274
    - [x] #9454
    - [x] #9482
    - [x] https://github.com/numba/numba/pull/9549
* [x] Check Numba's version support table documentation. Update via PR if
      needed.
  * [x] https://github.com/numba/numba/pull/9559
* [x] Review deprecation schedule and notices. Make PRs if need be. (`none needed`)
* [x] Merge change log changes.
    - [x] https://github.com/numba/numba/pull/9558
* [x] Create 0.60 release branch. https://github.com/numba/numba/tree/release0.60
* [x] Create PR against the release branch to make `numba/testing/main.py` https://github.com/numba/numba/pull/9561
      to refer to `origin/release0.60` instead of `origin/main`.
* [x] Dependency version pinning on release branch https://github.com/numba/numba/pull/9561
  * [x] Pin llvmlite to `0.43.*`.
  * [x] Pin NumPy if needed
  * [x] Pin TBB if needed (not needed)
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed. <strike>`numba_yaml_459`</strike> `numba_yaml_460 `
  * [x] Build farm CUDA testing has passed. <strike>`numba_smoketest_cuda_yaml_22`</strike> `numba_smoketest_cuda_yaml_227`
  * [x] Build farm wheel testing has passed. <strike>`numba_wheel_108`</strike> `numba_wheel_109`
* [x] Annotated tag `0.60.0rc1` on release branch (no `v` prefix). https://github.com/numba/numba/releases/tag/0.60.0rc1
* [x] Build and upload conda packages on buildfarm (check "upload"). `numba_yaml_461`
* [x] Build wheels and sdist on the buildfarm (check "upload"). `numba_wheel_111`
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`. https://anaconda.org/numba/numba/files?sort=basename&sort_order=desc&version=0.60.0rc1
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`). https://pypi.org/project/numba/0.60.0rc1/#files
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Initialize and verify ReadTheDocs build. https://numba.readthedocs.io/en/0.60.0rc1/
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers`. https://numba.discourse.group/t/ann-numba-0-60-0rc1-llvmlite-0-43-0rc1/2565
* [x] Post link to X and to Mastodon and... https://twitter.com/numba_jit/status/1790717466915577961

### Post Release:

* [x] Clean up `ci_artifacts` by moving files to sub-directories
* [x] Tag `0.61.0dev0` to start new development cycle on `main`. https://github.com/numba/numba/releases/tag/0.61.0dev0
* [x] Update llvmlite dependency via PR to `main`, PR includes version updates
      to:
  * [x] `setup.py`
  * [x] `numba/__init__.py`
  * [x] `docs/environment.yml`
  * [x] `buildscripts/incremental/setup_conda_environment.sh`
  * [x] `buildscripts/incremental/setup_conda_environment.cmd`
  * [x] `buildscripts/condarecipe.local/meta.yaml`
  * [x] https://github.com/numba/numba/pull/9575
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release. https://github.com/numba/numba/pull/9600
* [x] Close milestone (and then close this release issue).

**Comment by leofang** [comment]
Q: It seems all tasks are done (congrats! 🎉), is there an ETA for the rc1 release?

**Comment by esc** [comment]
> Q: It seems all tasks are done (congrats! 🎉), is there an ETA for the rc1 release?

Soon! 😇

**Comment by esc** [comment]
> The instructions for how to generate the change-log need to be added, it's now a combination of towncrier and using the script at: https://github.com/numba/numba/blob/main/maint/gitlog2changelog.py

Update, these instructions exist already: https://github.com/numba/numba/pull/9367 -- we just need to add a link to them from the release checklist template.

**Comment by esc** [comment]
Note to self: describe in more detail how to pin NumPy and how to pin llvmlite in the template.

**Comment by esc** [comment]
Note to self: describe in more detail how to add the changelog PR to the list of PRs.

**Comment by esc** [comment]
This release has been delayed due to discovering a release critical issue. We hope to resolve this on Monday and the target date to tag both Numba and llvmlite is now the 14th of may.

**Comment by esc** [comment]
> This release has been delayed due to discovering a release critical issue. We hope to resolve this on Monday and the target date to tag both Numba and llvmlite is now the 14th of may.

https://github.com/numba/numba/pull/9568

**Comment by esc** [comment]
The release process has resumed.

**Comment by jakirkham** [comment]
Am seeing a GH tag for [`0.60.0rc1`]( https://github.com/numba/numba/releases/tag/0.60.0rc1 )

Also seeing packages for...

* [conda]( https://anaconda.org/numba/numba/files?version=0.60.0rc1 )
* [pip]( https://pypi.org/project/numba/0.60.0rc1/#files )

Is there anything else still needed here?

**Comment by gmarkall** [comment]
> Am seeing a GH tag for [`0.60.0rc1`](https://github.com/numba/numba/releases/tag/0.60.0rc1)
> 
> Also seeing packages for...
> 
>     * [conda](https://anaconda.org/numba/numba/files?version=0.60.0rc1)
> 
>     * [pip](https://pypi.org/project/numba/0.60.0rc1/#files)
> 
> 
> Is there anything else still needed here?

A review of https://github.com/conda-forge/llvmlite-feedstock/pull/86 wouldn't go amiss :-)

Then I can do the Numba 0.60.0rc1 PR on conda-forge.
