### ISSUE TITLE
Numba 0.61.0rc1 Checklist

### ISSUE THREAD

**Issue by kc611** [numba/numba#9777]
## Numba 0.61.0rc1

* [x] Merge to main.
    - [x] Remaining Pull-Requests from milestone: https://github.com/numba/numba/milestone/81
* [x] Check Numba's version support table documentation. Update via PR if
      needed. (https://github.com/numba/numba/pull/9800)
* [x] Review deprecation schedule and notices. Make PRs if need be.
* [x] Create changelog using instructions at: docs/source/developer/release.rst
* [x] Merge change log changes.
    - [x] "PR with changelog entries". (https://github.com/numba/numba/pull/9800)
* [x] Create 0.61 release branch.
* [x] Create PR against the release branch to make `numba/testing/main.py`
      to refer to `origin/release0.61` instead of `origin/main`. (https://github.com/numba/numba/pull/9804)
* [x] Dependency version pinning on release branch (https://github.com/numba/numba/pull/9804)
  * [x] Pin llvmlite to `0.44.*`.
  * [x] Pin NumPy if needed
  * [x] Pin TBB if needed
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed.
  * [x] Build farm CUDA testing has passed.
  * [x] Build farm wheel testing has passed.
  * [ ] Pre-tag testing through `conda-forge`: https://github.com/numba/numba/issues/9271
* [x] Annotated tag `0.61.0rc1` on release branch (no `v` prefix). https://github.com/numba/numba/releases/tag/0.61.0rc1
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels and sdist on the buildfarm (check "upload").
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`. (https://anaconda.org/numba/numba/files?version=0.61.0rc1)
   * [x] Upload Windows Packages
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`). (https://pypi.org/project/numba/0.61.0rc1/)
  * [x] Upload Windows Packages 
* [x] Verify wheels for all platforms arrived on PyPi.
  * [x] Verify Windows Packages
* [x] Initialize and verify ReadTheDocs build. https://numba.readthedocs.io/en/0.61.0rc1/
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers`. https://numba.discourse.group/t/ann-numba-0-61-0rc1-and-llvmlite-0-44-0rc1-are-out/2816
* [x] Post link to X and to Mastodon and... https://x.com/numba_jit/status/1862409597694218464

### Post Release:

* [x] Clean up `ci_artifacts` by moving files to sub-directories
* [x] Tag `0.62.0dev0` to start new development cycle on `main`.
* [x] Update llvmlite dependency via PR to `main`, PR includes version updates
      to:
  * [x] `setup.py`
  * [x] `numba/__init__.py`
  * [x] `docs/environment.yml`
  * [x] `buildscripts/incremental/setup_conda_environment.sh`
  * [x] `buildscripts/incremental/setup_conda_environment.cmd`
  * [x] `buildscripts/condarecipe.local/meta.yaml`
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release. 
   * [x] https://github.com/numba/numba/issues/9777#issuecomment-2486160243
   * [x] https://github.com/numba/numba/pull/9847
* [x] Close milestone (and then close this release issue).
* [x] Closes #9792

**Comment by filbranden** [comment]
Any updates on release 0.61? I'm hoping to unblock upgrade to Numpy 2.1 but that's currently blocked on numba 0.61 getting released. Thanks!

**Comment by stuartarchibald** [comment]
Carrying forward a note from the maintainer meeting today. The `review deprecation schedule and notices` task needs an wording update to capture that deprecation notices will be kept in the docs for the version of the release where the deprecation code was removed and one subsequent release, i.e. remove deprecation notices for releases more than one release ago.

**Comment by esc** [comment]
The checklist is lacking the bullet regarding creating a snapshot of the build farm, the "other" worflow does have it included:

https://github.com/numba/numba/blob/main/.github/ISSUE_TEMPLATE/sub_rc_checklist.md?plain=1#L43

**Comment by RoyiAvital** [comment]
Will this version support NumPy 2.2?

**Comment by alippai** [comment]
@RoyiAvital @jarey said the rc1 is limited to <2.2: https://github.com/numba/numba/issues/9792#issuecomment-2528787784

**Comment by esc** [comment]
> @RoyiAvital @jarey said the rc1 is limited to <2.2: [#9792 (comment)](https://github.com/numba/numba/issues/9792#issuecomment-2528787784)

RC1 is indeed limited to 2.2 -- this NumPy was released right in the middle of the Numba release process. As far as I know, we have not yet decided if we have capacity to test and fix Numba for NumPy 2.2 as part of the 0.61.0 release.

**Comment by esc** [comment]
> > @RoyiAvital @jarey said the rc1 is limited to <2.2: [#9792 (comment)](https://github.com/numba/numba/issues/9792#issuecomment-2528787784)
> 
> RC1 is indeed limited to 2.2 -- this NumPy was released right in the middle of the Numba release process. As far as I know, we have not yet decided if we have capacity to test and fix Numba for NumPy 2.2 as part of the 0.61.0 release.

We will try to include NumPy 2.2 support on the final.

**Comment by esc** [comment]
As a heads up here: we identified some issues with RC1 -- so we will release an RC2. This will however delay the final release which is now expected in early 2025.

**Comment by artpelling** [comment]
> As a heads up here: we identified some issues with RC1 -- so we will release an RC2. This will however delay the final release which is now expected in early 2025.

When can we expect a release of RC1?

**Comment by jarey** [comment]
> > As a heads up here: we identified some issues with RC1 -- so we will release an RC2. This will however delay the final release which is now expected in early 2025.
> 
> When can we expect a release of RC1?

0.61.0rc1 is already available on pypi, but of course it is a release candidate so not production ready. It may unblock some use-cases if needes, but may be used with extreme caution, specially in production scenarios.

**Comment by filbranden** [comment]
> As a heads up here: we identified some issues with RC1 -- so we will release an RC2

Would you be able to share more information about the issues identified in RC1? Thanks!

**Comment by stuartarchibald** [comment]
@filbranden perhaps take a look at the respective rc2 milestones for Numba and llvmlite? They will contain the related issues and patches.

**Comment by esc** [comment]
> > > @RoyiAvital @jarey said the rc1 is limited to <2.2: [#9792 (comment)](https://github.com/numba/numba/issues/9792#issuecomment-2528787784)
> > 
> > 
> > RC1 is indeed limited to 2.2 -- this NumPy was released right in the middle of the Numba release process. As far as I know, we have not yet decided if we have capacity to test and fix Numba for NumPy 2.2 as part of the 0.61.0 release.
> 
> We will try to include NumPy 2.2 support on the final.

Unfortunately, it turned out that support for NumPy 2.2 is more work than originally anticipated. Hence the decision was taken yesterday that 0.61.0 will actually NOT have support for NumPy 2.2.

The test results are here: https://github.com/numba/numba/pull/9836#issuecomment-2531856352

The feature request to support this NumPy version is here: https://github.com/numba/numba/issues/9838

**Comment by esc** [comment]
> > As a heads up here: we identified some issues with RC1 -- so we will release an RC2
> 
> Would you be able to share more information about the issues identified in RC1? Thanks!

Yes, you can read about the reported issues in the thread regarding RC1 on discourse:

https://numba.discourse.group/t/ann-numba-0-61-0rc1-and-llvmlite-0-44-0rc1-are-out/2816/6

Also, the two milestones for the RC2s contain all the issues that need fixing from RC1:

https://github.com/numba/numba/milestone/86

https://github.com/numba/llvmlite/milestone/28

**Comment by esc** [comment]
@kc611 the updates for the release checklist are here: https://github.com/numba/numba/pull/9847

**Comment by esc** [comment]
This is a wrap, finally.
