### ISSUE TITLE
Numba 0.61.0rc2 Checklist

### ISSUE THREAD

**Issue by kc611** [numba/numba#9842]
## numba 0.61.0rc2

* [x] Cherry-pick items from the 0.61.0rc2 milestone into a cherry-pick PR.
* [ ] ~Update the "version support table" in the documentation with the final
  release date (FINAL ONLY) and add to cherry-pick PR~
* [x] Update `CHANGE_LOG` on cherry-pick PR
* [x] Check if any dependency pinnings need an update (e.g. NumPy)
* [x] Approve cherry-pick PR
* [x] Merge cherry-pick PR to release0.61 release branch.
  * [x] https://github.com/numba/numba/pull/9843
* [ ] ~Review, merge and check execution of release notebook. (FINAL ONLY)~
* [x] Run the HEAD of the release branch through the build farm and confirm:
  * [x] Build farm CPU testing has passed. (`numba_yaml_513` is sufficient)
  * [ ] ~Build farm CUDA testing has passed~
  * [x] Build farm wheel testing has passed
* [x] Annotated tag 0.61.0rc2 on release branch (no `v` prefix).
  `git tag -am "Version 0.61.0rc2" "0.61.0rc2"`
* [x] Build and upload conda packages on buildfarm (check `upload`). (`numba_yaml_514`)
* [x] Build wheels and sdist on the buildfarm (check "upload"). (`numba_wheel_119`)
* [x] Verify packages uploaded to Anaconda Cloud and move to
  `numba/label/main`. (https://anaconda.org/numba/numba/files?version=0.61.0rc2)
* [x] Upload wheels and sdist to PyPI (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi. (https://pypi.org/project/numba/0.61.0rc2/#files)
* [x] Verify ReadTheDocs build. (https://numba.readthedocs.io/en/0.61.0rc2/)
* [ ] ~Create a release on Github at https://github.com/numba/numba/releases (FINAL ONLY).~
* [x] Post link to X and to Mastodon and...
  * [x] https://x.com/numba_jit/status/1869741054024630767 
* [x] Post announcement to discourse group and ping the release testers group
  using `@RC_Testers` (RC ONLY).
  * [x] https://numba.discourse.group/t/ann-numba-0-61-0rc2-and-llvmlite-0-44-0rc2-are-out/2845
* [ ] ~~Post link to python-announce-list@python.org.~~ FINAL ONLY

### Post release

* [ ] ~~Cherry-pick change-log and version support table modifications to `main`~~ FINAL ONLY
* [x] Snapshot Build Farm config
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [ ] ~~Update release checklist template with any additional bullet points that
      may have arisen during the release.~~ None
* [ ] ~~Ping Anaconda Distro team to trigger a build for `defaults`~~ (FINAL ONLY).
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Looks like a few more `FINAL ONLY` clauses could be added to the checklist.
